-- VALTRIX about_sections contentJa/Ko/Fr/Ar 补全（专业翻译，与 content/contentEn 对应）
\set ON_ERROR_STOP on

UPDATE about_sections SET "contentJa" = $ja$[{"heading":"VALTRIXについて","paragraphs":["VALTRIXは、半導体、バイオ医薬、LED/ディスプレイ、太陽光、水素エネルギー業界向けに超高純度流体制御部品を精密製造するメーカーです。製品はVCR面シール継手、溶接継手、ダイヤフラムバルブ、減圧レギュレーター、逆止弁、ガスフィルターを網羅し、すべて316Lステンレス鋼製で、電解研磨表面仕上げを選択できます。","すべての部品は材料の完全なトレーサビリティのもとで生産され、ISOクラス4/5のクリーンルームで組立後、二重袋包装の前に100%ヘリウムリークテストを実施します。長年のOEM製造経験に根ざしたこの品質管理が、VALTRIX部品を最先端半導体ファブの汚染管理要件に適合させています。","単品の継手から完成したガスパネルまで、VALTRIXはエンジニアリング支援、カスタム製造、そして世界中への迅速で信頼性の高い納品を提供します。"]}]$ja$,
"contentKo" = $ko$[{"heading":"VALTRIX 소개","paragraphs":["VALTRIX는 반도체, 바이오의약, LED/디스플레이, 태양광, 수소에너지 산업을 위한 초고순도 유체 제어 부품을 정밀 제조하는 기업입니다. 제품은 VCR 페이스 씰 피팅, 용접 피팅, 다이어프램 밸브, 감압 레귤레이터, 체크 밸브, 가스 필터를 아우르며, 모두 316L 스테인리스 스틸로 제조되고 전해연마 표면 옵션을 제공합니다.","모든 부품은 완전한 소재 이력 추적 하에 생산되며, ISO 클래스 4/5 클린룸에서 조립된 후 이중 포장 전 100% 헬륨 누설 검사를 거칩니다. 수년간의 OEM 제조 경험에 뿌리를 둔 이 품질 관리 덕분에 VALTRIX 부품은 첨단 반도체 팹의 오염 관리 요구를 충족합니다.","단일 피팅부터 완전한 가스 패널까지, VALTRIX는 엔지니어링 지원, 맞춤 제조, 그리고 전 세계로의 신속하고 신뢰할 수 있는 납품을 제공합니다."]}]$ko$,
"contentFr" = $fr$[{"heading":"À propos de VALTRIX","paragraphs":["VALTRIX est un fabricant de précision de composants de contrôle fluidique ultra-haute pureté pour les secteurs des semi-conducteurs, de la biopharmacie, des LED/écrans, du solaire et de l'hydrogène. Notre gamme couvre les raccords d'étanchéité de surface VCR, les raccords soudés, les vannes à membrane, les détendeurs, les clapets antiretour et les filtres à gaz — tous fabriqués en acier inoxydable 316L avec options de surface électropolie.","Chaque composant est produit avec une traçabilité totale des matériaux, assemblé en salle blanche ISO classe 4/5, et soumis à un test d'étanchéité à l'hélium à 100 % avant double ensachage. Cette rigueur, issue de nombreuses années d'expérience en fabrication OEM, permet aux composants VALTRIX de répondre aux exigences de contrôle de la contamination des fabs de semi-conducteurs les plus avancés.","Du raccord unique aux panneaux de gaz complets, VALTRIX fournit un support d'ingénierie, une fabrication sur mesure et une livraison rapide et fiable dans le monde entier."]}]$fr$,
"contentAr" = $ar$[{"heading":"حول VALTRIX","paragraphs":["VALTRIX هي شركة تصنيع دقيقة لمكونات التحكم في السوائل فائقة النقاء لصناعات أشباه الموصلات والأدوية الحيوية وشاشات LED والطاقة الشمسية والهيدروجين. تغطي مجموعتنا وصلات ختم الوجه VCR والوصلات الملحومة وصمامات الحجاب الحاجز ومنظمات الضغط وصمامات عدم الرجوع ومرشحات الغاز — جميعها مصنوعة من الفولاذ المقاوم للصدأ 316L مع خيارات سطح مصقول كهربائيًا.","يتم إنتاج كل مكون مع تتبع كامل للمواد، ويُجمَّع في غرفة نظيفة من الفئة ISO 4/5، ويخضع لاختبار تسرب الهيليوم بنسبة 100% قبل التغليف المزدوج. هذا الانضباط، المتجذر في سنوات من خبرة التصنيع OEM، هو ما يسمح لمكونات VALTRIX بتلبية متطلبات التحكم في التلوث لمصانع أشباه الموصلات المتقدمة.","من وصلة واحدة إلى لوحات الغاز الكاملة، تقدم VALTRIX الدعم الهندسي والتصنيع المخصص والتسليم السريع الموثوق في جميع أنحاء العالم."]}]$ar$
WHERE id=1;

UPDATE about_sections SET "contentJa" = $ja$[{"heading":"成長の歩み","paragraphs":["VALTRIXは、海外OEM顧客にサービスを提供する精密加工工場から、超高純度流体制御部品の専門メーカーへと成長しました。","CNC加工、電解研磨、クリーンルーム組立への継続的な投資を通じて、VALTRIXは現在、VCR面シール継手、ダイヤフラムバルブ、レギュレーターを世界中の半導体・高純度プロセス産業に供給しています。"]}]$ja$,
"contentKo" = $ko$[{"heading":"발전 연혁","paragraphs":["VALTRIX는 해외 OEM 고객을 위한 정밀 가공 공장에서 초고순도 유체 제어 부품 전문 제조업체로 성장했습니다.","CNC 가공, 전해연마, 클린룸 조립에 대한 지속적인 투자를 통해 VALTRIX는 현재 VCR 페이스 씰 피팅, 다이어프램 밸브, 레귤레이터를 전 세계 반도체 및 고순도 공정 산업에 공급하고 있습니다."]}]$ko$,
"contentFr" = $fr$[{"heading":"Notre histoire","paragraphs":["VALTRIX est passé d'un atelier d'usinage de précision au service de clients OEM internationaux à un fabricant dédié de composants de contrôle fluidique ultra-haute pureté.","Grâce à des investissements continus dans l'usinage CNC, l'électropolissage et l'assemblage en salle blanche, VALTRIX fournit désormais des raccords d'étanchéité de surface VCR, des vannes à membrane et des détendeurs aux industries des semi-conducteurs et des procédés haute pureté dans le monde entier."]}]$fr$,
"contentAr" = $ar$[{"heading":"مسيرتنا","paragraphs":["نمت VALTRIX من ورشة تصنيع دقيقة تخدم عملاء OEM الدوليين إلى شركة تصنيع متخصصة في مكونات التحكم في السوائل فائقة النقاء.","من خلال الاستثمار المستمر في التصنيع باستخدام الحاسب الآلي CNC والتلميع الكهربائي والتجميع في الغرف النظيفة، تزود VALTRIX الآن وحدات ختم الوجه VCR وصمامات الحجاب الحاجز ومنظمات الضغط لصناعات أشباه الموصلات والعمليات عالية النقاء حول العالم."]}]$ar$
WHERE id=2;

UPDATE about_sections SET "contentJa" = $ja$[{"heading":"品質と認証","paragraphs":["VALTRIXは、高純度流体制御部品の設計、加工、組立、検査、納品を網羅するISO 9001認証の品質マネジメントシステムを運用しています。","各生産ロットは100%ヘリウム質量分析計リークテスト（感度1×10⁻¹⁰ scc/s）を実施し、全工程で表面粗さ測定とパーティクル管理を行っています。材料には完全なミル証明書のトレーサビリティがあり、組立品はISOクラス4/5のクリーンルーム環境で梱包されます。"]}]$ja$,
"contentKo" = $ko$[{"heading":"품질 및 인증","paragraphs":["VALTRIX는 고순도 유체 제어 부품의 설계, 가공, 조립, 시험, 납품을 포괄하는 ISO 9001 인증 품질 관리 시스템을 운영합니다.","각 생산 로트는 100% 헬륨 질량 분석기 누설 검사(감도 1×10⁻¹⁰ scc/s)를 거치며, 모든 단계에서 표면 거칠기 측정과 입자 관리를 수행합니다. 소재는 완전한 밀 증명서 추적성을 갖추며, 조립품은 ISO 클래스 4/5 클린룸 환경에서 포장됩니다."]}]$ko$,
"contentFr" = $fr$[{"heading":"Qualité et certifications","paragraphs":["VALTRIX exploite un système de management de la qualité certifié ISO 9001 couvrant la conception, l'usinage, l'assemblage, les essais et la livraison de composants de contrôle fluidique haute pureté.","Chaque lot de production est soumis à un test d'étanchéité à l'hélium par spectrométrie de masse à 100 % (sensibilité à 1×10⁻¹⁰ scc/s), avec mesure de la rugosité de surface et contrôle des particules à chaque étape. Les matériaux disposent d'une traçabilité complète par certificat d'usine, et les assemblages sont conditionnés en salle blanche ISO classe 4/5."]}]$fr$,
"contentAr" = $ar$[{"heading":"الجودة والشهادات","paragraphs":["تدير VALTRIX نظام إدارة جودة معتمد وفق ISO 9001 يغطي تصميم وتصنيع وتجميع واختبار وتسليم مكونات التحكم في السوائل عالية النقاء.","تخضع كل دفعة إنتاج لاختبار تسرب الهيليوم بنسبة 100% بمقياس الطيف الكتلي (حساسية تصل إلى 1×10⁻¹⁰ scc/s)، مع قياس خشونة السطح والتحكم في الجسيمات في كل مرحلة. تتمتع المواد بتتبع كامل بشهادات المطحنة، وتُعبأ التجميعات في ظروف غرفة نظيفة من الفئة ISO 4/5."]}]$ar$
WHERE id=3;

UPDATE about_sections SET "contentJa" = $ja$[{"heading":"お問い合わせ","paragraphs":["製品のお問い合わせ、選定サポート、OEM/ODMプロジェクト、ビジネス提携など、いつでもVALTRIXチームにお問い合わせください。1営業日以内にご返信いたします。"]}]$ja$,
"contentKo" = $ko$[{"heading":"문의하기","paragraphs":["제품 문의, 선정 지원, OEM/ODM 프로젝트 또는 비즈니스 협력은 언제든지 VALTRIX 팀에 문의해 주세요. 영업일 기준 1일 이내에 답변드립니다."]}]$ko$,
"contentFr" = $fr$[{"heading":"Contactez-nous","paragraphs":["Pour toute demande de renseignements sur les produits, support de sélection, projets OEM/ODM ou coopération commerciale, contactez l'équipe VALTRIX à tout moment. Nous répondons sous un jour ouvré."]}]$fr$,
"contentAr" = $ar$[{"heading":"اتصل بنا","paragraphs":["للاستفسارات عن المنتجات أو دعم الاختيار أو مشاريع OEM/ODM أو التعاون التجاري، يرجى التواصل مع فريق VALTRIX في أي وقت. نرد خلال يوم عمل واحد."]}]$ar$
WHERE id=4;
