// GEO地区和城市数据
// 地区默认：中国、印度、美国、俄罗斯、中东地区
// 城市：各地区主要123线城市

export interface GeoRegion {
  code: string
  name: string
  nameEn: string
  cities: GeoCity[]
}

export interface GeoCity {
  name: string
  nameEn: string
  tier?: string // 一线、新一线、二线、三线
}

export const GEO_REGIONS: GeoRegion[] = [
  {
    code: 'cn',
    name: '中国',
    nameEn: 'China',
    cities: [
      // 一线城市
      { name: '北京', nameEn: 'Beijing', tier: '一线' },
      { name: '上海', nameEn: 'Shanghai', tier: '一线' },
      { name: '广州', nameEn: 'Guangzhou', tier: '一线' },
      { name: '深圳', nameEn: 'Shenzhen', tier: '一线' },
      // 新一线城市
      { name: '成都', nameEn: 'Chengdu', tier: '新一线' },
      { name: '杭州', nameEn: 'Hangzhou', tier: '新一线' },
      { name: '重庆', nameEn: 'Chongqing', tier: '新一线' },
      { name: '武汉', nameEn: 'Wuhan', tier: '新一线' },
      { name: '西安', nameEn: "Xi'an", tier: '新一线' },
      { name: '苏州', nameEn: 'Suzhou', tier: '新一线' },
      { name: '天津', nameEn: 'Tianjin', tier: '新一线' },
      { name: '南京', nameEn: 'Nanjing', tier: '新一线' },
      { name: '长沙', nameEn: 'Changsha', tier: '新一线' },
      { name: '郑州', nameEn: 'Zhengzhou', tier: '新一线' },
      { name: '东莞', nameEn: 'Dongguan', tier: '新一线' },
      { name: '青岛', nameEn: 'Qingdao', tier: '新一线' },
      { name: '沈阳', nameEn: 'Shenyang', tier: '新一线' },
      { name: '宁波', nameEn: 'Ningbo', tier: '新一线' },
      { name: '昆明', nameEn: 'Kunming', tier: '新一线' },
      // 二线城市
      { name: '无锡', nameEn: 'Wuxi', tier: '二线' },
      { name: '佛山', nameEn: 'Foshan', tier: '二线' },
      { name: '合肥', nameEn: 'Hefei', tier: '二线' },
      { name: '大连', nameEn: 'Dalian', tier: '二线' },
      { name: '福州', nameEn: 'Fuzhou', tier: '二线' },
      { name: '厦门', nameEn: 'Xiamen', tier: '二线' },
      { name: '哈尔滨', nameEn: 'Harbin', tier: '二线' },
      { name: '济南', nameEn: 'Jinan', tier: '二线' },
      { name: '温州', nameEn: 'Wenzhou', tier: '二线' },
      { name: '南宁', nameEn: 'Nanning', tier: '二线' },
      { name: '长春', nameEn: 'Changchun', tier: '二线' },
      { name: '泉州', nameEn: 'Quanzhou', tier: '二线' },
      { name: '石家庄', nameEn: 'Shijiazhuang', tier: '二线' },
      { name: '贵阳', nameEn: 'Guiyang', tier: '二线' },
      { name: '南昌', nameEn: 'Nanchang', tier: '二线' },
      { name: '金华', nameEn: 'Jinhua', tier: '二线' },
      { name: '惠州', nameEn: 'Huizhou', tier: '二线' },
      { name: '珠海', nameEn: 'Zhuhai', tier: '二线' },
      { name: '中山', nameEn: 'Zhongshan', tier: '二线' },
      { name: '台州', nameEn: 'Taizhou', tier: '二线' },
      { name: '烟台', nameEn: 'Yantai', tier: '二线' },
      { name: '兰州', nameEn: 'Lanzhou', tier: '二线' },
      { name: '绍兴', nameEn: 'Shaoxing', tier: '二线' },
      { name: '海口', nameEn: 'Haikou', tier: '二线' },
      { name: '扬州', nameEn: 'Yangzhou', tier: '二线' },
      // 三线城市（主要）
      { name: '洛阳', nameEn: 'Luoyang', tier: '三线' },
      { name: '唐山', nameEn: 'Tangshan', tier: '三线' },
      { name: '呼和浩特', nameEn: 'Hohhot', tier: '三线' },
      { name: '乌鲁木齐', nameEn: 'Urumqi', tier: '三线' },
      { name: '银川', nameEn: 'Yinchuan', tier: '三线' },
      { name: '西宁', nameEn: 'Xining', tier: '三线' },
      { name: '拉萨', nameEn: 'Lhasa', tier: '三线' },
      { name: '太原', nameEn: 'Taiyuan', tier: '三线' },
      { name: '保定', nameEn: 'Baoding', tier: '三线' },
      { name: '廊坊', nameEn: 'Langfang', tier: '三线' },
      { name: '唐山', nameEn: 'Tangshan', tier: '三线' },
      { name: '秦皇岛', nameEn: 'Qinhuangdao', tier: '三线' },
      { name: '邯郸', nameEn: 'Handan', tier: '三线' },
      { name: '沧州', nameEn: 'Cangzhou', tier: '三线' },
      { name: '邢台', nameEn: 'Xingtai', tier: '三线' },
      { name: '张家口', nameEn: 'Zhangjiakou', tier: '三线' },
      { name: '承德', nameEn: 'Chengde', tier: '三线' },
      { name: '衡水', nameEn: 'Hengshui', tier: '三线' },
      { name: '包头', nameEn: 'Baotou', tier: '三线' },
      { name: '鄂尔多斯', nameEn: 'Ordos', tier: '三线' },
      { name: '赤峰', nameEn: 'Chifeng', tier: '三线' },
      { name: '通辽', nameEn: 'Tongliao', tier: '三线' },
      { name: '呼伦贝尔', nameEn: 'Hulunbuir', tier: '三线' },
      { name: '巴彦淖尔', nameEn: 'Bayannur', tier: '三线' },
      { name: '乌兰察布', nameEn: 'Ulanqab', tier: '三线' },
      { name: '兴安盟', nameEn: 'Hinggan', tier: '三线' },
      { name: '锡林郭勒', nameEn: 'Xilingol', tier: '三线' },
      { name: '阿拉善', nameEn: 'Alxa', tier: '三线' },
      { name: '鞍山', nameEn: 'Anshan', tier: '三线' },
      { name: '抚顺', nameEn: 'Fushun', tier: '三线' },
      { name: '本溪', nameEn: 'Benxi', tier: '三线' },
      { name: '丹东', nameEn: 'Dandong', tier: '三线' },
      { name: '锦州', nameEn: 'Jinzhou', tier: '三线' },
      { name: '营口', nameEn: 'Yingkou', tier: '三线' },
      { name: '阜新', nameEn: 'Fuxin', tier: '三线' },
      { name: '辽阳', nameEn: 'Liaoyang', tier: '三线' },
      { name: '盘锦', nameEn: 'Panjin', tier: '三线' },
      { name: '铁岭', nameEn: 'Tieling', tier: '三线' },
      { name: '朝阳', nameEn: 'Chaoyang', tier: '三线' },
      { name: '葫芦岛', nameEn: 'Huludao', tier: '三线' },
      { name: '吉林', nameEn: 'Jilin', tier: '三线' },
      { name: '四平', nameEn: 'Siping', tier: '三线' },
      { name: '辽源', nameEn: 'Liaoyuan', tier: '三线' },
      { name: '通化', nameEn: 'Tonghua', tier: '三线' },
      { name: '白山', nameEn: 'Baishan', tier: '三线' },
      { name: '松原', nameEn: 'Songyuan', tier: '三线' },
      { name: '白城', nameEn: 'Baicheng', tier: '三线' },
      { name: '延边', nameEn: 'Yanbian', tier: '三线' },
      { name: '齐齐哈尔', nameEn: 'Qiqihar', tier: '三线' },
      { name: '鸡西', nameEn: 'Jixi', tier: '三线' },
      { name: '鹤岗', nameEn: 'Hegang', tier: '三线' },
      { name: '双鸭山', nameEn: 'Shuangyashan', tier: '三线' },
      { name: '大庆', nameEn: 'Daqing', tier: '三线' },
      { name: '伊春', nameEn: 'Yichun', tier: '三线' },
      { name: '佳木斯', nameEn: 'Jiamusi', tier: '三线' },
      { name: '七台河', nameEn: 'Qitaihe', tier: '三线' },
      { name: '牡丹江', nameEn: 'Mudanjiang', tier: '三线' },
      { name: '黑河', nameEn: 'Heihe', tier: '三线' },
      { name: '绥化', nameEn: 'Suihua', tier: '三线' },
      { name: '大兴安岭', nameEn: 'Daxinganling', tier: '三线' },
      { name: '常州', nameEn: 'Changzhou', tier: '三线' },
      { name: '南通', nameEn: 'Nantong', tier: '三线' },
      { name: '徐州', nameEn: 'Xuzhou', tier: '三线' },
      { name: '盐城', nameEn: 'Yancheng', tier: '三线' },
      { name: '扬州', nameEn: 'Yangzhou', tier: '三线' },
      { name: '镇江', nameEn: 'Zhenjiang', tier: '三线' },
      { name: '泰州', nameEn: 'Taizhou', tier: '三线' },
      { name: '宿迁', nameEn: 'Suqian', tier: '三线' },
      { name: '连云港', nameEn: 'Lianyungang', tier: '三线' },
      { name: '淮安', nameEn: 'Huaian', tier: '三线' },
      { name: '盐城', nameEn: 'Yancheng', tier: '三线' },
      { name: '湖州', nameEn: 'Huzhou', tier: '三线' },
      { name: '嘉兴', nameEn: 'Jiaxing', tier: '三线' },
      { name: '绍兴', nameEn: 'Shaoxing', tier: '三线' },
      { name: '金华', nameEn: 'Jinhua', tier: '三线' },
      { name: '衢州', nameEn: 'Quzhou', tier: '三线' },
      { name: '舟山', nameEn: 'Zhoushan', tier: '三线' },
      { name: '台州', nameEn: 'Taizhou', tier: '三线' },
      { name: '丽水', nameEn: 'Lishui', tier: '三线' },
      { name: '芜湖', nameEn: 'Wuhu', tier: '三线' },
      { name: '蚌埠', nameEn: 'Bengbu', tier: '三线' },
      { name: '淮南', nameEn: 'Huainan', tier: '三线' },
      { name: '马鞍山', nameEn: 'Maanshan', tier: '三线' },
      { name: '淮北', nameEn: 'Huaibei', tier: '三线' },
      { name: '铜陵', nameEn: 'Tongling', tier: '三线' },
      { name: '安庆', nameEn: 'Anqing', tier: '三线' },
      { name: '黄山', nameEn: 'Huangshan', tier: '三线' },
      { name: '滁州', nameEn: 'Chuzhou', tier: '三线' },
      { name: '阜阳', nameEn: 'Fuyang', tier: '三线' },
      { name: '宿州', nameEn: 'Suzhou', tier: '三线' },
      { name: '六安', nameEn: "Lu'an", tier: '三线' },
      { name: '亳州', nameEn: 'Bozhou', tier: '三线' },
      { name: '池州', nameEn: 'Chizhou', tier: '三线' },
      { name: '宣城', nameEn: 'Xuancheng', tier: '三线' },
      { name: '莆田', nameEn: 'Putian', tier: '三线' },
      { name: '三明', nameEn: 'Sanming', tier: '三线' },
      { name: '漳州', nameEn: 'Zhangzhou', tier: '三线' },
      { name: '南平', nameEn: 'Nanping', tier: '三线' },
      { name: '龙岩', nameEn: 'Longyan', tier: '三线' },
      { name: '宁德', nameEn: 'Ningde', tier: '三线' },
      { name: '景德镇', nameEn: 'Jingdezhen', tier: '三线' },
      { name: '萍乡', nameEn: 'Pingxiang', tier: '三线' },
      { name: '九江', nameEn: 'Jiujiang', tier: '三线' },
      { name: '新余', nameEn: 'Xinyu', tier: '三线' },
      { name: '鹰潭', nameEn: 'Yingtan', tier: '三线' },
      { name: '赣州', nameEn: 'Ganzhou', tier: '三线' },
      { name: '吉安', nameEn: "Ji'an", tier: '三线' },
      { name: '宜春', nameEn: 'Yichun', tier: '三线' },
      { name: '抚州', nameEn: 'Fuzhou', tier: '三线' },
      { name: '上饶', nameEn: 'Shangrao', tier: '三线' },
      { name: '淄博', nameEn: 'Zibo', tier: '三线' },
      { name: '枣庄', nameEn: 'Zaozhuang', tier: '三线' },
      { name: '东营', nameEn: 'Dongying', tier: '三线' },
      { name: '潍坊', nameEn: 'Weifang', tier: '三线' },
      { name: '济宁', nameEn: 'Jining', tier: '三线' },
      { name: '泰安', nameEn: "Tai'an", tier: '三线' },
      { name: '威海', nameEn: 'Weihai', tier: '三线' },
      { name: '日照', nameEn: 'Rizhao', tier: '三线' },
      { name: '临沂', nameEn: 'Linyi', tier: '三线' },
      { name: '德州', nameEn: 'Dezhou', tier: '三线' },
      { name: '聊城', nameEn: 'Liaocheng', tier: '三线' },
      { name: '滨州', nameEn: 'Binzhou', tier: '三线' },
      { name: '菏泽', nameEn: 'Heze', tier: '三线' },
      { name: '洛阳', nameEn: 'Luoyang', tier: '三线' },
      { name: '开封', nameEn: 'Kaifeng', tier: '三线' },
      { name: '平顶山', nameEn: 'Pingdingshan', tier: '三线' },
      { name: '安阳', nameEn: 'Anyang', tier: '三线' },
      { name: '鹤壁', nameEn: 'Hebi', tier: '三线' },
      { name: '新乡', nameEn: 'Xinxiang', tier: '三线' },
      { name: '焦作', nameEn: 'Jiaozuo', tier: '三线' },
      { name: '濮阳', nameEn: 'Puyang', tier: '三线' },
      { name: '许昌', nameEn: 'Xuchang', tier: '三线' },
      { name: '漯河', nameEn: 'Luohe', tier: '三线' },
      { name: '三门峡', nameEn: 'Sanmenxia', tier: '三线' },
      { name: '南阳', nameEn: 'Nanyang', tier: '三线' },
      { name: '商丘', nameEn: 'Shangqiu', tier: '三线' },
      { name: '信阳', nameEn: 'Xinyang', tier: '三线' },
      { name: '周口', nameEn: 'Zhoukou', tier: '三线' },
      { name: '驻马店', nameEn: 'Zhumadian', tier: '三线' },
      { name: '济源', nameEn: 'Jiyuan', tier: '三线' },
      { name: '黄石', nameEn: 'Huangshi', tier: '三线' },
      { name: '十堰', nameEn: 'Shiyan', tier: '三线' },
      { name: '宜昌', nameEn: 'Yichang', tier: '三线' },
      { name: '襄阳', nameEn: 'Xiangyang', tier: '三线' },
      { name: '鄂州', nameEn: 'Ezhou', tier: '三线' },
      { name: '荆门', nameEn: 'Jingmen', tier: '三线' },
      { name: '孝感', nameEn: 'Xiaogan', tier: '三线' },
      { name: '荆州', nameEn: 'Jingzhou', tier: '三线' },
      { name: '黄冈', nameEn: 'Huanggang', tier: '三线' },
      { name: '咸宁', nameEn: 'Xianning', tier: '三线' },
      { name: '随州', nameEn: 'Suizhou', tier: '三线' },
      { name: '恩施', nameEn: 'Enshi', tier: '三线' },
      { name: '仙桃', nameEn: 'Xiantao', tier: '三线' },
      { name: '潜江', nameEn: 'Qianjiang', tier: '三线' },
      { name: '天门', nameEn: 'Tianmen', tier: '三线' },
      { name: '神农架', nameEn: 'Shennongjia', tier: '三线' },
      { name: '株洲', nameEn: 'Zhuzhou', tier: '三线' },
      { name: '湘潭', nameEn: 'Xiangtan', tier: '三线' },
      { name: '衡阳', nameEn: 'Hengyang', tier: '三线' },
      { name: '邵阳', nameEn: 'Shaoyang', tier: '三线' },
      { name: '岳阳', nameEn: 'Yueyang', tier: '三线' },
      { name: '常德', nameEn: 'Changde', tier: '三线' },
      { name: '张家界', nameEn: 'Zhangjiajie', tier: '三线' },
      { name: '益阳', nameEn: 'Yiyang', tier: '三线' },
      { name: '郴州', nameEn: 'Chenzhou', tier: '三线' },
      { name: '永州', nameEn: 'Yongzhou', tier: '三线' },
      { name: '怀化', nameEn: 'Huaihua', tier: '三线' },
      { name: '娄底', nameEn: 'Loudi', tier: '三线' },
      { name: '湘西', nameEn: 'Xiangxi', tier: '三线' },
      { name: '韶关', nameEn: 'Shaoguan', tier: '三线' },
      { name: '湛江', nameEn: 'Zhanjiang', tier: '三线' },
      { name: '肇庆', nameEn: 'Zhaoqing', tier: '三线' },
      { name: '江门', nameEn: 'Jiangmen', tier: '三线' },
      { name: '茂名', nameEn: 'Maoming', tier: '三线' },
      { name: '惠州', nameEn: 'Huizhou', tier: '三线' },
      { name: '梅州', nameEn: 'Meizhou', tier: '三线' },
      { name: '汕尾', nameEn: 'Shanwei', tier: '三线' },
      { name: '河源', nameEn: 'Heyuan', tier: '三线' },
      { name: '阳江', nameEn: 'Yangjiang', tier: '三线' },
      { name: '清远', nameEn: 'Qingyuan', tier: '三线' },
      { name: '东莞', nameEn: 'Dongguan', tier: '三线' },
      { name: '中山', nameEn: 'Zhongshan', tier: '三线' },
      { name: '潮州', nameEn: 'Chaozhou', tier: '三线' },
      { name: '揭阳', nameEn: 'Jieyang', tier: '三线' },
      { name: '云浮', nameEn: 'Yunfu', tier: '三线' },
      { name: '南宁', nameEn: 'Nanning', tier: '三线' },
      { name: '柳州', nameEn: 'Liuzhou', tier: '三线' },
      { name: '桂林', nameEn: 'Guilin', tier: '三线' },
      { name: '梧州', nameEn: 'Wuzhou', tier: '三线' },
      { name: '北海', nameEn: 'Beihai', tier: '三线' },
      { name: '防城港', nameEn: 'Fangchenggang', tier: '三线' },
      { name: '钦州', nameEn: 'Qinzhou', tier: '三线' },
      { name: '贵港', nameEn: 'Guigang', tier: '三线' },
      { name: '玉林', nameEn: 'Yulin', tier: '三线' },
      { name: '百色', nameEn: 'Baise', tier: '三线' },
      { name: '贺州', nameEn: 'Hezhou', tier: '三线' },
      { name: '河池', nameEn: 'Hechi', tier: '三线' },
      { name: '来宾', nameEn: 'Laibin', tier: '三线' },
      { name: '崇左', nameEn: 'Chongzuo', tier: '三线' },
      { name: '海口', nameEn: 'Haikou', tier: '三线' },
      { name: '三亚', nameEn: 'Sanya', tier: '三线' },
      { name: '三沙', nameEn: 'Sansha', tier: '三线' },
      { name: '儋州', nameEn: 'Danzhou', tier: '三线' },
      { name: '五指山', nameEn: 'Wuzhishan', tier: '三线' },
      { name: '琼海', nameEn: 'Qionghai', tier: '三线' },
      { name: '文昌', nameEn: 'Wenchang', tier: '三线' },
      { name: '万宁', nameEn: 'Wanning', tier: '三线' },
      { name: '东方', nameEn: 'Dongfang', tier: '三线' },
      { name: '成都', nameEn: 'Chengdu', tier: '三线' },
      { name: '自贡', nameEn: 'Zigong', tier: '三线' },
      { name: '攀枝花', nameEn: 'Panzhihua', tier: '三线' },
      { name: '泸州', nameEn: 'Luzhou', tier: '三线' },
      { name: '德阳', nameEn: 'Deyang', tier: '三线' },
      { name: '绵阳', nameEn: 'Mianyang', tier: '三线' },
      { name: '广元', nameEn: 'Guangyuan', tier: '三线' },
      { name: '遂宁', nameEn: 'Suining', tier: '三线' },
      { name: '内江', nameEn: 'Neijiang', tier: '三线' },
      { name: '乐山', nameEn: 'Leshan', tier: '三线' },
      { name: '南充', nameEn: 'Nanchong', tier: '三线' },
      { name: '眉山', nameEn: 'Meishan', tier: '三线' },
      { name: '宜宾', nameEn: 'Yibin', tier: '三线' },
      { name: '广安', nameEn: "Guang'an", tier: '三线' },
      { name: '达州', nameEn: 'Dazhou', tier: '三线' },
      { name: '雅安', nameEn: "Ya'an", tier: '三线' },
      { name: '巴中', nameEn: 'Bazhong', tier: '三线' },
      { name: '资阳', nameEn: 'Ziyang', tier: '三线' },
      { name: '阿坝', nameEn: 'Aba', tier: '三线' },
      { name: '甘孜', nameEn: 'Ganzi', tier: '三线' },
      { name: '凉山', nameEn: 'Liangshan', tier: '三线' },
      { name: '贵阳', nameEn: 'Guiyang', tier: '三线' },
      { name: '六盘水', nameEn: 'Liupanshui', tier: '三线' },
      { name: '遵义', nameEn: 'Zunyi', tier: '三线' },
      { name: '安顺', nameEn: 'Anshun', tier: '三线' },
      { name: '毕节', nameEn: 'Bijie', tier: '三线' },
      { name: '铜仁', nameEn: 'Tongren', tier: '三线' },
      { name: '黔西南', nameEn: 'Qianxinan', tier: '三线' },
      { name: '黔东南', nameEn: 'Qiandongnan', tier: '三线' },
      { name: '黔南', nameEn: 'Qiannan', tier: '三线' },
      { name: '昆明', nameEn: 'Kunming', tier: '三线' },
      { name: '曲靖', nameEn: 'Qujing', tier: '三线' },
      { name: '玉溪', nameEn: 'Yuxi', tier: '三线' },
      { name: '保山', nameEn: 'Baoshan', tier: '三线' },
      { name: '昭通', nameEn: 'Zhaotong', tier: '三线' },
      { name: '丽江', nameEn: 'Lijiang', tier: '三线' },
      { name: '普洱', nameEn: "Pu'er", tier: '三线' },
      { name: '临沧', nameEn: 'Lincang', tier: '三线' },
      { name: '楚雄', nameEn: 'Chuxiong', tier: '三线' },
      { name: '红河', nameEn: 'Honghe', tier: '三线' },
      { name: '文山', nameEn: 'Wenshan', tier: '三线' },
      { name: '西双版纳', nameEn: 'Xishuangbanna', tier: '三线' },
      { name: '大理', nameEn: 'Dali', tier: '三线' },
      { name: '德宏', nameEn: 'Dehong', tier: '三线' },
      { name: '怒江', nameEn: 'Nujiang', tier: '三线' },
      { name: '迪庆', nameEn: 'Diqing', tier: '三线' },
      { name: '拉萨', nameEn: 'Lhasa', tier: '三线' },
      { name: '日喀则', nameEn: 'Shigatse', tier: '三线' },
      { name: '昌都', nameEn: 'Qamdo', tier: '三线' },
      { name: '林芝', nameEn: 'Nyingchi', tier: '三线' },
      { name: '山南', nameEn: 'Shannan', tier: '三线' },
      { name: '那曲', nameEn: 'Naqu', tier: '三线' },
      { name: '阿里', nameEn: 'Ali', tier: '三线' },
      { name: '西安', nameEn: "Xi'an", tier: '三线' },
      { name: '铜川', nameEn: 'Tongchuan', tier: '三线' },
      { name: '宝鸡', nameEn: 'Baoji', tier: '三线' },
      { name: '咸阳', nameEn: 'Xianyang', tier: '三线' },
      { name: '渭南', nameEn: 'Weinan', tier: '三线' },
      { name: '延安', nameEn: "Yan'an", tier: '三线' },
      { name: '汉中', nameEn: 'Hanzhong', tier: '三线' },
      { name: '榆林', nameEn: 'Yulin', tier: '三线' },
      { name: '安康', nameEn: 'Ankang', tier: '三线' },
      { name: '商洛', nameEn: 'Shangluo', tier: '三线' },
      { name: '兰州', nameEn: 'Lanzhou', tier: '三线' },
      { name: '嘉峪关', nameEn: 'Jiayuguan', tier: '三线' },
      { name: '金昌', nameEn: 'Jinchang', tier: '三线' },
      { name: '白银', nameEn: 'Baiyin', tier: '三线' },
      { name: '天水', nameEn: 'Tianshui', tier: '三线' },
      { name: '武威', nameEn: 'Wuwei', tier: '三线' },
      { name: '张掖', nameEn: 'Zhangye', tier: '三线' },
      { name: '平凉', nameEn: 'Pingliang', tier: '三线' },
      { name: '酒泉', nameEn: 'Jiuquan', tier: '三线' },
      { name: '庆阳', nameEn: 'Qingyang', tier: '三线' },
      { name: '定西', nameEn: 'Dingxi', tier: '三线' },
      { name: '陇南', nameEn: 'Longnan', tier: '三线' },
      { name: '临夏', nameEn: 'Linxia', tier: '三线' },
      { name: '甘南', nameEn: 'Gannan', tier: '三线' },
      { name: '西宁', nameEn: 'Xining', tier: '三线' },
      { name: '海东', nameEn: 'Haidong', tier: '三线' },
      { name: '海北', nameEn: 'Haibei', tier: '三线' },
      { name: '黄南', nameEn: 'Huangnan', tier: '三线' },
      { name: '海南州', nameEn: 'Hainan', tier: '三线' },
      { name: '果洛', nameEn: 'Golog', tier: '三线' },
      { name: '玉树', nameEn: 'Yushu', tier: '三线' },
      { name: '海西', nameEn: 'Haixi', tier: '三线' },
      { name: '银川', nameEn: 'Yinchuan', tier: '三线' },
      { name: '石嘴山', nameEn: 'Shizuishan', tier: '三线' },
      { name: '吴忠', nameEn: 'Wuzhong', tier: '三线' },
      { name: '固原', nameEn: 'Guyuan', tier: '三线' },
      { name: '中卫', nameEn: 'Zhongwei', tier: '三线' },
      { name: '乌鲁木齐', nameEn: 'Urumqi', tier: '三线' },
      { name: '克拉玛依', nameEn: 'Karamay', tier: '三线' },
      { name: '吐鲁番', nameEn: 'Turpan', tier: '三线' },
      { name: '哈密', nameEn: 'Hami', tier: '三线' },
      { name: '昌吉', nameEn: 'Changji', tier: '三线' },
      { name: '博尔塔拉', nameEn: 'Bortala', tier: '三线' },
      { name: '巴音郭楞', nameEn: 'Bayingolin', tier: '三线' },
      { name: '阿克苏', nameEn: 'Aksu', tier: '三线' },
      { name: '克孜勒苏', nameEn: 'Kizilsu', tier: '三线' },
      { name: '喀什', nameEn: 'Kashgar', tier: '三线' },
      { name: '和田', nameEn: 'Hotan', tier: '三线' },
      { name: '伊犁', nameEn: 'Ili', tier: '三线' },
      { name: '塔城', nameEn: 'Tacheng', tier: '三线' },
      { name: '阿勒泰', nameEn: 'Altay', tier: '三线' },
      { name: '石河子', nameEn: 'Shihezi', tier: '三线' },
      { name: '阿拉尔', nameEn: 'Aral', tier: '三线' },
      { name: '图木舒克', nameEn: 'Tumxuk', tier: '三线' },
      { name: '五家渠', nameEn: 'Wujiaqu', tier: '三线' },
      { name: '北屯', nameEn: 'Beitun', tier: '三线' },
      { name: '铁门关', nameEn: 'Tiemenguan', tier: '三线' },
      { name: '双河', nameEn: 'Shuanghe', tier: '三线' },
      { name: '可克达拉', nameEn: 'Kokdala', tier: '三线' },
      { name: '昆玉', nameEn: 'Kunyu', tier: '三线' },
      { name: '胡杨河', nameEn: 'Huyanghe', tier: '三线' },
    ],
  },
  {
    code: 'in',
    name: '印度',
    nameEn: 'India',
    cities: [
      { name: '新德里', nameEn: 'New Delhi', tier: '一线' },
      { name: '孟买', nameEn: 'Mumbai', tier: '一线' },
      { name: '班加罗尔', nameEn: 'Bangalore', tier: '一线' },
      { name: '海得拉巴', nameEn: 'Hyderabad', tier: '新一线' },
      { name: '钦奈', nameEn: 'Chennai', tier: '新一线' },
      { name: '加尔各答', nameEn: 'Kolkata', tier: '新一线' },
      { name: '浦那', nameEn: 'Pune', tier: '新一线' },
      { name: '艾哈迈达巴德', nameEn: 'Ahmedabad', tier: '新一线' },
      { name: '斋浦尔', nameEn: 'Jaipur', tier: '二线' },
      { name: '勒克瑙', nameEn: 'Lucknow', tier: '二线' },
      { name: '坎普尔', nameEn: 'Kanpur', tier: '二线' },
      { name: '那格浦尔', nameEn: 'Nagpur', tier: '二线' },
      { name: '印多尔', nameEn: 'Indore', tier: '二线' },
      { name: '巴特那', nameEn: 'Patna', tier: '二线' },
      { name: '博帕尔', nameEn: 'Bhopal', tier: '二线' },
      { name: '维沙卡帕特南', nameEn: 'Visakhapatnam', tier: '二线' },
      { name: '卢迪亚纳', nameEn: 'Ludhiana', tier: '三线' },
      { name: '昌迪加尔', nameEn: 'Chandigarh', tier: '三线' },
      { name: '苏拉特', nameEn: 'Surat', tier: '三线' },
      { name: '瓦多达拉', nameEn: 'Vadodara', tier: '三线' },
      { name: '拉杰果德', nameEn: 'Rajkot', tier: '三线' },
      { name: '贾姆讷格尔', nameEn: 'Jamnagar', tier: '三线' },
      { name: '哥印拜陀', nameEn: 'Coimbatore', tier: '三线' },
      { name: '马杜赖', nameEn: 'Madurai', tier: '三线' },
      { name: '特里凡得琅', nameEn: 'Thiruvananthapuram', tier: '三线' },
      { name: '科钦', nameEn: 'Kochi', tier: '三线' },
      { name: '高知', nameEn: 'Kozhikode', tier: '三线' },
      { name: '迈索尔', nameEn: 'Mysore', tier: '三线' },
      { name: '门格洛尔', nameEn: 'Mangalore', tier: '三线' },
      { name: '贝尔高姆', nameEn: 'Belgaum', tier: '三线' },
      { name: '胡布利', nameEn: 'Hubli', tier: '三线' },
      { name: '古尔冈', nameEn: 'Gurgaon', tier: '三线' },
      { name: '诺伊达', nameEn: 'Noida', tier: '三线' },
      { name: '法里达巴德', nameEn: 'Faridabad', tier: '三线' },
      { name: '加济阿巴德', nameEn: 'Ghaziabad', tier: '三线' },
      { name: '密拉特', nameEn: 'Meerut', tier: '三线' },
      { name: '瓦拉纳西', nameEn: 'Varanasi', tier: '三线' },
      { name: '阿拉哈巴德', nameEn: 'Allahabad', tier: '三线' },
      { name: '阿格拉', nameEn: 'Agra', tier: '三线' },
      { name: '莫拉达巴德', nameEn: 'Moradabad', tier: '三线' },
      { name: '巴雷利', nameEn: 'Bareilly', tier: '三线' },
      { name: '阿拉布加尔', nameEn: 'Aligarh', tier: '三线' },
      { name: '贾朗达尔', nameEn: 'Jalandhar', tier: '三线' },
      { name: '阿姆利则', nameEn: 'Amritsar', tier: '三线' },
      { name: '巴廷达', nameEn: 'Bathinda', tier: '三线' },
      { name: '帕蒂亚拉', nameEn: 'Patiala', tier: '三线' },
      { name: '哥打', nameEn: 'Kota', tier: '三线' },
      { name: '焦特布尔', nameEn: 'Jodhpur', tier: '三线' },
      { name: '乌代布尔', nameEn: 'Udaipur', tier: '三线' },
      { name: '阿杰梅尔', nameEn: 'Ajmer', tier: '三线' },
      { name: '比卡内尔', nameEn: 'Bikaner', tier: '三线' },
      { name: '赖布尔', nameEn: 'Raipur', tier: '三线' },
      { name: '比拉斯布尔', nameEn: 'Bilaspur', tier: '三线' },
      { name: '杜尔格', nameEn: 'Durg', tier: '三线' },
      { name: '兰契', nameEn: 'Ranchi', tier: '三线' },
      { name: '詹谢普尔', nameEn: 'Jamshedpur', tier: '三线' },
      { name: '丹巴德', nameEn: 'Dhanbad', tier: '三线' },
      { name: '博卡罗', nameEn: 'Bokaro', tier: '三线' },
      { name: '布巴内斯瓦尔', nameEn: 'Bhubaneswar', tier: '三线' },
      { name: '克塔克', nameEn: 'Cuttack', tier: '三线' },
      { name: '鲁尔克拉', nameEn: 'Rourkela', tier: '三线' },
      { name: '古瓦哈提', nameEn: 'Guwahati', tier: '三线' },
      { name: '西隆', nameEn: 'Shillong', tier: '三线' },
      { name: '阿加尔塔拉', nameEn: 'Agartala', tier: '三线' },
      { name: '伊塔那噶', nameEn: 'Itanagar', tier: '三线' },
      { name: '科希马', nameEn: 'Kohima', tier: '三线' },
      { name: '因帕尔', nameEn: 'Imphal', tier: '三线' },
      { name: '艾藻尔', nameEn: 'Aizawl', tier: '三线' },
      { name: '甘托克', nameEn: 'Gangtok', tier: '三线' },
      { name: '本地治里', nameEn: 'Puducherry', tier: '三线' },
      { name: '昌迪加尔', nameEn: 'Chandigarh', tier: '三线' },
      { name: '德里', nameEn: 'Delhi', tier: '一线' },
    ],
  },
  {
    code: 'us',
    name: '美国',
    nameEn: 'United States',
    cities: [
      { name: '纽约', nameEn: 'New York', tier: '一线' },
      { name: '洛杉矶', nameEn: 'Los Angeles', tier: '一线' },
      { name: '芝加哥', nameEn: 'Chicago', tier: '一线' },
      { name: '休斯顿', nameEn: 'Houston', tier: '新一线' },
      { name: '凤凰城', nameEn: 'Phoenix', tier: '新一线' },
      { name: '费城', nameEn: 'Philadelphia', tier: '新一线' },
      { name: '圣安东尼奥', nameEn: 'San Antonio', tier: '新一线' },
      { name: '圣迭戈', nameEn: 'San Diego', tier: '新一线' },
      { name: '达拉斯', nameEn: 'Dallas', tier: '新一线' },
      { name: '圣何塞', nameEn: 'San Jose', tier: '新一线' },
      { name: '奥斯汀', nameEn: 'Austin', tier: '新一线' },
      { name: '杰克逊维尔', nameEn: 'Jacksonville', tier: '二线' },
      { name: '旧金山', nameEn: 'San Francisco', tier: '二线' },
      { name: '哥伦布', nameEn: 'Columbus', tier: '二线' },
      { name: '夏洛特', nameEn: 'Charlotte', tier: '二线' },
      { name: '印第安纳波利斯', nameEn: 'Indianapolis', tier: '二线' },
      { name: '西雅图', nameEn: 'Seattle', tier: '二线' },
      { name: '丹佛', nameEn: 'Denver', tier: '二线' },
      { name: '华盛顿', nameEn: 'Washington', tier: '二线' },
      { name: '波士顿', nameEn: 'Boston', tier: '二线' },
      { name: '埃尔帕索', nameEn: 'El Paso', tier: '二线' },
      { name: '纳什维尔', nameEn: 'Nashville', tier: '二线' },
      { name: '底特律', nameEn: 'Detroit', tier: '二线' },
      { name: '俄克拉荷马城', nameEn: 'Oklahoma City', tier: '二线' },
      { name: '波特兰', nameEn: 'Portland', tier: '二线' },
      { name: '拉斯维加斯', nameEn: 'Las Vegas', tier: '二线' },
      { name: '孟菲斯', nameEn: 'Memphis', tier: '二线' },
      { name: '路易斯维尔', nameEn: 'Louisville', tier: '二线' },
      { name: '巴尔的摩', nameEn: 'Baltimore', tier: '二线' },
      { name: '密尔沃基', nameEn: 'Milwaukee', tier: '二线' },
      { name: '阿尔伯克基', nameEn: 'Albuquerque', tier: '二线' },
      { name: '图森', nameEn: 'Tucson', tier: '二线' },
      { name: '弗雷斯诺', nameEn: 'Fresno', tier: '三线' },
      { name: '萨克拉门托', nameEn: 'Sacramento', tier: '三线' },
      { name: '堪萨斯城', nameEn: 'Kansas City', tier: '三线' },
      { name: '长滩', nameEn: 'Long Beach', tier: '三线' },
      { name: '梅萨', nameEn: 'Mesa', tier: '三线' },
      { name: '亚特兰大', nameEn: 'Atlanta', tier: '三线' },
      { name: '科罗拉多斯普林斯', nameEn: 'Colorado Springs', tier: '三线' },
      { name: '罗利', nameEn: 'Raleigh', tier: '三线' },
      { name: '奥马哈', nameEn: 'Omaha', tier: '三线' },
      { name: '迈阿密', nameEn: 'Miami', tier: '三线' },
      { name: '弗吉尼亚比奇', nameEn: 'Virginia Beach', tier: '三线' },
      { name: '奥克兰', nameEn: 'Oakland', tier: '三线' },
      { name: '塔尔萨', nameEn: 'Tulsa', tier: '三线' },
      { name: '明尼阿波利斯', nameEn: 'Minneapolis', tier: '三线' },
      { name: '阿灵顿', nameEn: 'Arlington', tier: '三线' },
      { name: '新奥尔良', nameEn: 'New Orleans', tier: '三线' },
      { name: '威奇托', nameEn: 'Wichita', tier: '三线' },
      { name: '克利夫兰', nameEn: 'Cleveland', tier: '三线' },
      { name: '坦帕', nameEn: 'Tampa', tier: '三线' },
      { name: '贝克斯菲尔德', nameEn: 'Bakersfield', tier: '三线' },
      { name: '奥罗拉', nameEn: 'Aurora', tier: '三线' },
      { name: '火奴鲁鲁', nameEn: 'Honolulu', tier: '三线' },
      { name: '阿纳海姆', nameEn: 'Anaheim', tier: '三线' },
      { name: '圣安娜', nameEn: 'Santa Ana', tier: '三线' },
      { name: '圣路易斯', nameEn: 'St. Louis', tier: '三线' },
      { name: '匹兹堡', nameEn: 'Pittsburgh', tier: '三线' },
      { name: '里弗赛德', nameEn: 'Riverside', tier: '三线' },
      { name: '辛辛那提', nameEn: 'Cincinnati', tier: '三线' },
      { name: '列克星敦', nameEn: 'Lexington', tier: '三线' },
      { name: '斯托克顿', nameEn: 'Stockton', tier: '三线' },
      { name: '安克雷奇', nameEn: 'Anchorage', tier: '三线' },
      { name: '亨德森', nameEn: 'Henderson', tier: '三线' },
      { name: '泽西市', nameEn: 'Jersey City', tier: '三线' },
      { name: '圣巴勃罗', nameEn: 'Saint Paul', tier: '三线' },
      { name: '丘拉维斯塔', nameEn: 'Chula Vista', tier: '三线' },
      { name: '麦迪逊', nameEn: 'Madison', tier: '三线' },
      { name: '布法罗', nameEn: 'Buffalo', tier: '三线' },
      { name: '科珀斯克里斯蒂', nameEn: 'Corpus Christi', tier: '三线' },
      { name: '拉伯克', nameEn: 'Lubbock', tier: '三线' },
      { name: '韦恩堡', nameEn: 'Fort Wayne', tier: '三线' },
      { name: '林肯', nameEn: 'Lincoln', tier: '三线' },
      { name: '图尔萨', nameEn: 'Tulsa', tier: '三线' },
      { name: '弗里蒙特', nameEn: 'Fremont', tier: '三线' },
      { name: '格伦代尔', nameEn: 'Glendale', tier: '三线' },
      { name: '加兰', nameEn: 'Garland', tier: '三线' },
      { name: '海沃德', nameEn: 'Hayward', tier: '三线' },
      { name: '雷诺', nameEn: 'Reno', tier: '三线' },
      { name: '拉雷多', nameEn: 'Laredo', tier: '三线' },
      { name: '达勒姆', nameEn: 'Durham', tier: '三线' },
      { name: '巴吞鲁日', nameEn: 'Baton Rouge', tier: '三线' },
      { name: '博伊西', nameEn: 'Boise', tier: '三线' },
      { name: '北拉斯维加斯', nameEn: 'North Las Vegas', tier: '三线' },
      { name: '吉尔伯特', nameEn: 'Gilbert', tier: '三线' },
      { name: '诺福克', nameEn: 'Norfolk', tier: '三线' },
      { name: '罗切斯特', nameEn: 'Rochester', tier: '三线' },
      { name: '埃斯孔迪多', nameEn: 'Escondido', tier: '三线' },
      { name: '塞勒姆', nameEn: 'Salem', tier: '三线' },
      { name: '科斯塔梅萨', nameEn: 'Costa Mesa', tier: '三线' },
      { name: '帕萨迪纳', nameEn: 'Pasadena', tier: '三线' },
      { name: '奥兰多', nameEn: 'Orlando', tier: '三线' },
      { name: '欧弗兰帕克', nameEn: 'Overland Park', tier: '三线' },
      { name: '克拉克斯维尔', nameEn: 'Clarksville', tier: '三线' },
      { name: '棕榈湾', nameEn: 'Palm Bay', tier: '三线' },
      { name: '萨利纳斯', nameEn: 'Salinas', tier: '三线' },
      { name: '波莫纳', nameEn: 'Pomona', tier: '三线' },
      { name: '好莱坞', nameEn: 'Hollywood', tier: '三线' },
      { name: '埃尔蒙特', nameEn: 'El Monte', tier: '三线' },
      { name: '康科德', nameEn: 'Concord', tier: '三线' },
      { name: '托伦斯', nameEn: 'Torrance', tier: '三线' },
      { name: '帕姆代尔', nameEn: 'Palmdale', tier: '三线' },
      { name: '圣克拉拉', nameEn: 'Santa Clara', tier: '三线' },
      { name: '圣罗莎', nameEn: 'Santa Rosa', tier: '三线' },
      { name: '里士满', nameEn: 'Richmond', tier: '三线' },
      { name: '安条克', nameEn: 'Antioch', tier: '三线' },
      { name: '瓦列霍', nameEn: 'Vallejo', tier: '三线' },
      { name: '莫德斯托', nameEn: 'Modesto', tier: '三线' },
      { name: '奥克斯纳德', nameEn: 'Oxnard', tier: '三线' },
      { name: '文图拉', nameEn: 'Ventura', tier: '三线' },
      { name: '圣巴巴拉', nameEn: 'Santa Barbara', tier: '三线' },
      { name: '圣玛丽亚', nameEn: 'Santa Maria', tier: '三线' },
      { name: '洛代', nameEn: 'Lodi', tier: '三线' },
      { name: '特雷西', nameEn: 'Tracy', tier: '三线' },
      { name: '曼特卡', nameEn: 'Manteca', tier: '三线' },
      { name: '帕特森', nameEn: 'Patterson', tier: '三线' },
      { name: '洛斯巴诺斯', nameEn: 'Los Banos', tier: '三线' },
      { name: '门多塔', nameEn: 'Mendota', tier: '三线' },
      { name: '科灵加', nameEn: 'Coalinga', tier: '三线' },
      { name: '金斯堡', nameEn: 'Kingsburg', tier: '三线' },
      { name: '塞尔马', nameEn: 'Selma', tier: '三线' },
      { name: '里德利', nameEn: 'Reedley', tier: '三线' },
      { name: '埃克塞特', nameEn: 'Exeter', tier: '三线' },
      { name: '波特维尔', nameEn: 'Porterville', tier: '三线' },
      { name: '维塞利亚', nameEn: 'Visalia', tier: '三线' },
      { name: '汉福德', nameEn: 'Hanford', tier: '三线' },
      { name: '莱莫尔', nameEn: 'Lemoore', tier: '三线' },
      { name: '科克伦', nameEn: 'Corcoran', tier: '三线' },
    ],
  },
  {
    code: 'ru',
    name: '俄罗斯',
    nameEn: 'Russia',
    cities: [
      { name: '莫斯科', nameEn: 'Moscow', tier: '一线' },
      { name: '圣彼得堡', nameEn: 'Saint Petersburg', tier: '一线' },
      { name: '新西伯利亚', nameEn: 'Novosibirsk', tier: '新一线' },
      { name: '叶卡捷琳堡', nameEn: 'Yekaterinburg', tier: '新一线' },
      { name: '喀山', nameEn: 'Kazan', tier: '新一线' },
      { name: '下诺夫哥罗德', nameEn: 'Nizhny Novgorod', tier: '新一线' },
      { name: '车里雅宾斯克', nameEn: 'Chelyabinsk', tier: '新一线' },
      { name: '萨马拉', nameEn: 'Samara', tier: '新一线' },
      { name: '鄂木斯克', nameEn: 'Omsk', tier: '新一线' },
      { name: '顿河畔罗斯托夫', nameEn: 'Rostov-on-Don', tier: '新一线' },
      { name: '乌法', nameEn: 'Ufa', tier: '二线' },
      { name: '克拉斯诺亚尔斯克', nameEn: 'Krasnoyarsk', tier: '二线' },
      { name: '沃罗涅日', nameEn: 'Voronezh', tier: '二线' },
      { name: '彼尔姆', nameEn: 'Perm', tier: '二线' },
      { name: '伏尔加格勒', nameEn: 'Volgograd', tier: '二线' },
      { name: '克拉斯诺达尔', nameEn: 'Krasnodar', tier: '二线' },
      { name: '萨拉托夫', nameEn: 'Saratov', tier: '二线' },
      { name: '秋明', nameEn: 'Tyumen', tier: '二线' },
      { name: '陶里亚蒂', nameEn: 'Tolyatti', tier: '二线' },
      { name: '伊热夫斯克', nameEn: 'Izhevsk', tier: '二线' },
      { name: '巴尔瑙尔', nameEn: 'Barnaul', tier: '三线' },
      { name: '乌里扬诺夫斯克', nameEn: 'Ulyanovsk', tier: '三线' },
      { name: '伊尔库茨克', nameEn: 'Irkutsk', tier: '三线' },
      { name: '哈巴罗夫斯克', nameEn: 'Khabarovsk', tier: '三线' },
      { name: '雅罗斯拉夫尔', nameEn: 'Yaroslavl', tier: '三线' },
      { name: '符拉迪沃斯托克', nameEn: 'Vladivostok', tier: '三线' },
      { name: '马哈奇卡拉', nameEn: 'Makhachkala', tier: '三线' },
      { name: '托木斯克', nameEn: 'Tomsk', tier: '三线' },
      { name: '奥伦堡', nameEn: 'Orenburg', tier: '三线' },
      { name: '克麦罗沃', nameEn: 'Kemerovo', tier: '三线' },
      { name: '新库兹涅茨克', nameEn: 'Novokuznetsk', tier: '三线' },
      { name: '梁赞', nameEn: 'Ryazan', tier: '三线' },
      { name: '阿斯特拉罕', nameEn: 'Astrakhan', tier: '三线' },
      { name: '卡马河畔切尔内', nameEn: 'Naberezhnye Chelny', tier: '三线' },
      { name: '奔萨', nameEn: 'Penza', tier: '三线' },
      { name: '利佩茨克', nameEn: 'Lipetsk', tier: '三线' },
      { name: '基洛夫', nameEn: 'Kirov', tier: '三线' },
      { name: '图拉', nameEn: 'Tula', tier: '三线' },
      { name: '切博克萨雷', nameEn: 'Cheboksary', tier: '三线' },
      { name: '布良斯克', nameEn: 'Bryansk', tier: '三线' },
      { name: '库尔斯克', nameEn: 'Kursk', tier: '三线' },
      { name: '伊万诺沃', nameEn: 'Ivanovo', tier: '三线' },
      { name: '马格尼托哥尔斯克', nameEn: 'Magnitogorsk', tier: '三线' },
      { name: '特维尔', nameEn: 'Tver', tier: '三线' },
      { name: '斯塔夫罗波尔', nameEn: 'Stavropol', tier: '三线' },
      { name: '斯摩棱斯克', nameEn: 'Smolensk', tier: '三线' },
      { name: '弗拉基米尔', nameEn: 'Vladimir', tier: '三线' },
      { name: '瑟克特夫卡尔', nameEn: 'Syktyvkar', tier: '三线' },
      { name: '摩尔曼斯克', nameEn: 'Murmansk', tier: '三线' },
      { name: '卡卢加', nameEn: 'Kaluga', tier: '三线' },
      { name: '萨兰斯克', nameEn: 'Saransk', tier: '三线' },
      { name: '库尔干', nameEn: 'Kurgan', tier: '三线' },
      { name: '斯米杜姆', nameEn: 'Smidovich', tier: '三线' },
      { name: '彼得罗扎沃茨克', nameEn: 'Petrozavodsk', tier: '三线' },
      { name: '塔甘罗格', nameEn: 'Taganrog', tier: '三线' },
      { name: '下塔吉尔', nameEn: 'Nizhny Tagil', tier: '三线' },
      { name: '诺夫哥罗德', nameEn: 'Veliky Novgorod', tier: '三线' },
      { name: '布拉茨克', nameEn: 'Bratsk', tier: '三线' },
      { name: '北德文斯克', nameEn: 'Severodvinsk', tier: '三线' },
      { name: '诺里尔斯克', nameEn: 'Norilsk', tier: '三线' },
      { name: '季霍列茨克', nameEn: 'Tikhoretsk', tier: '三线' },
      { name: '迈科普', nameEn: 'Maykop', tier: '三线' },
      { name: '纳尔奇克', nameEn: 'Nalchik', tier: '三线' },
      { name: '格罗兹尼', nameEn: 'Grozny', tier: '三线' },
      { name: '弗拉季高加索', nameEn: 'Vladikavkaz', tier: '三线' },
      { name: '卡斯皮斯克', nameEn: 'Kaspiysk', tier: '三线' },
      { name: '皮亚季戈尔斯克', nameEn: 'Pyatigorsk', tier: '三线' },
      { name: '涅温诺梅斯克', nameEn: 'Nevinnomyssk', tier: '三线' },
      { name: '叶先图基', nameEn: 'Yessentuki', tier: '三线' },
      { name: '基斯洛沃茨克', nameEn: 'Kislovodsk', tier: '三线' },
      { name: '切尔克斯克', nameEn: 'Cherkessk', tier: '三线' },
    ],
  },
  {
    code: 'me',
    name: '中东地区',
    nameEn: 'Middle East',
    cities: [
      { name: '迪拜', nameEn: 'Dubai', tier: '一线' },
      { name: '阿布扎比', nameEn: 'Abu Dhabi', tier: '一线' },
      { name: '利雅得', nameEn: 'Riyadh', tier: '一线' },
      { name: '吉达', nameEn: 'Jeddah', tier: '新一线' },
      { name: '多哈', nameEn: 'Doha', tier: '新一线' },
      { name: '科威特城', nameEn: 'Kuwait City', tier: '新一线' },
      { name: '麦纳麦', nameEn: 'Manama', tier: '新一线' },
      { name: '马斯喀特', nameEn: 'Muscat', tier: '新一线' },
      { name: '德黑兰', nameEn: 'Tehran', tier: '新一线' },
      { name: '伊斯坦布尔', nameEn: 'Istanbul', tier: '新一线' },
      { name: '安卡拉', nameEn: 'Ankara', tier: '新一线' },
      { name: '安曼', nameEn: 'Amman', tier: '二线' },
      { name: '贝鲁特', nameEn: 'Beirut', tier: '二线' },
      { name: '大马士革', nameEn: 'Damascus', tier: '二线' },
      { name: '巴格达', nameEn: 'Baghdad', tier: '二线' },
      { name: '耶路撒冷', nameEn: 'Jerusalem', tier: '二线' },
      { name: '特拉维夫', nameEn: 'Tel Aviv', tier: '二线' },
      { name: '加沙', nameEn: 'Gaza', tier: '二线' },
      { name: '萨那', nameEn: 'Sanaa', tier: '二线' },
      { name: '亚丁', nameEn: 'Aden', tier: '二线' },
      { name: '沙迦', nameEn: 'Sharjah', tier: '三线' },
      { name: '艾因', nameEn: 'Al Ain', tier: '三线' },
      { name: '阿治曼', nameEn: 'Ajman', tier: '三线' },
      { name: '富查伊拉', nameEn: 'Fujairah', tier: '三线' },
      { name: '哈伊马角', nameEn: 'Ras Al Khaimah', tier: '三线' },
      { name: '乌姆盖万', nameEn: 'Umm Al Quwain', tier: '三线' },
      { name: '麦加', nameEn: 'Mecca', tier: '三线' },
      { name: '麦地那', nameEn: 'Medina', tier: '三线' },
      { name: '达曼', nameEn: 'Dammam', tier: '三线' },
      { name: '塔伊夫', nameEn: 'Taif', tier: '三线' },
      { name: '胡富夫', nameEn: 'Hofuf', tier: '三线' },
      { name: '库拜尔', nameEn: 'Khobar', tier: '三线' },
      { name: '塔布克', nameEn: 'Tabuk', tier: '三线' },
      { name: '布赖代', nameEn: 'Buraidah', tier: '三线' },
      { name: '哈伊勒', nameEn: 'Hail', tier: '三线' },
      { name: '阿西尔', nameEn: 'Asir', tier: '三线' },
      { name: '季赞', nameEn: 'Jizan', tier: '三线' },
      { name: '纳季兰', nameEn: 'Najran', tier: '三线' },
      { name: '焦夫', nameEn: 'Al Jawf', tier: '三线' },
      { name: '巴哈', nameEn: 'Al Bahah', tier: '三线' },
      { name: '卡西姆', nameEn: 'Qassim', tier: '三线' },
      { name: '北部边疆', nameEn: 'Northern Borders', tier: '三线' },
      { name: '塞拉莱', nameEn: 'Salalah', tier: '三线' },
      { name: '苏哈尔', nameEn: 'Sohar', tier: '三线' },
      { name: '尼兹瓦', nameEn: 'Nizwa', tier: '三线' },
      { name: '鲁斯塔克', nameEn: 'Rustaq', tier: '三线' },
      { name: '伊卜里', nameEn: 'Ibri', tier: '三线' },
      { name: '苏尔', nameEn: 'Sur', tier: '三线' },
      { name: '布雷米', nameEn: 'Al Buraimi', tier: '三线' },
      { name: '穆桑达姆', nameEn: 'Musandam', tier: '三线' },
      { name: '巴士拉', nameEn: 'Basra', tier: '三线' },
      { name: '摩苏尔', nameEn: 'Mosul', tier: '三线' },
      { name: '埃尔比勒', nameEn: 'Erbil', tier: '三线' },
      { name: '基尔库克', nameEn: 'Kirkuk', tier: '三线' },
      { name: '纳杰夫', nameEn: 'Najaf', tier: '三线' },
      { name: '卡尔巴拉', nameEn: 'Karbala', tier: '三线' },
      { name: '苏莱曼尼亚', nameEn: 'Sulaymaniyah', tier: '三线' },
      { name: '费卢杰', nameEn: 'Fallujah', tier: '三线' },
      { name: '拉马迪', nameEn: 'Ramadi', tier: '三线' },
      { name: '提克里特', nameEn: 'Tikrit', tier: '三线' },
      { name: '萨迈拉', nameEn: 'Samarra', tier: '三线' },
      { name: '库特', nameEn: 'Kut', tier: '三线' },
      { name: '阿马拉', nameEn: 'Amarah', tier: '三线' },
      { name: '纳西里耶', nameEn: 'Nasiriyah', tier: '三线' },
      { name: '迪瓦尼耶', nameEn: 'Diwaniyah', tier: '三线' },
      { name: '希拉', nameEn: 'Hillah', tier: '三线' },
      { name: '巴古拜', nameEn: 'Baqubah', tier: '三线' },
      { name: '曼代利', nameEn: 'Mandali', tier: '三线' },
      { name: '哈奈根', nameEn: 'Khanaqin', tier: '三线' },
      { name: '杜胡克', nameEn: 'Duhok', tier: '三线' },
      { name: '扎胡', nameEn: 'Zakho', tier: '三线' },
      { name: '哈拉布贾', nameEn: 'Halabja', tier: '三线' },
      { name: '昌切尔', nameEn: 'Chamchamal', tier: '三线' },
      { name: '拉尼耶', nameEn: 'Ranya', tier: '三线' },
      { name: '佩什达', nameEn: 'Peshder', tier: '三线' },
      { name: '马什哈德', nameEn: 'Mashhad', tier: '三线' },
      { name: '伊斯法罕', nameEn: 'Isfahan', tier: '三线' },
      { name: '卡拉季', nameEn: 'Karaj', tier: '三线' },
      { name: '设拉子', nameEn: 'Shiraz', tier: '三线' },
      { name: '大不里士', nameEn: 'Tabriz', tier: '三线' },
      { name: '阿瓦士', nameEn: 'Ahvaz', tier: '三线' },
      { name: '库姆', nameEn: 'Qom', tier: '三线' },
      { name: '拉什特', nameEn: 'Rasht', tier: '三线' },
      { name: '克尔曼沙赫', nameEn: 'Kermanshah', tier: '三线' },
      { name: '乌尔米耶', nameEn: 'Urmia', tier: '三线' },
      { name: '扎黑丹', nameEn: 'Zahedan', tier: '三线' },
      { name: '哈马丹', nameEn: 'Hamadan', tier: '三线' },
      { name: '克尔曼', nameEn: 'Kerman', tier: '三线' },
      { name: '亚兹德', nameEn: 'Yazd', tier: '三线' },
      { name: '阿尔达比勒', nameEn: 'Ardabil', tier: '三线' },
      { name: '赞詹', nameEn: 'Zanjan', tier: '三线' },
      { name: '加兹温', nameEn: 'Qazvin', tier: '三线' },
      { name: '阿巴斯港', nameEn: 'Bandar Abbas', tier: '三线' },
      { name: '塞姆南', nameEn: 'Semnan', tier: '三线' },
      { name: '布什尔', nameEn: 'Bushehr', tier: '三线' },
      { name: '戈尔甘', nameEn: 'Gorgan', tier: '三线' },
      { name: '萨里', nameEn: 'Sari', tier: '三线' },
      { name: '阿莫勒', nameEn: 'Amol', tier: '三线' },
      { name: '瑙沙赫尔', nameEn: 'Noshahr', tier: '三线' },
      { name: '恰卢斯', nameEn: 'Chalus', tier: '三线' },
      { name: '拉姆萨尔', nameEn: 'Ramsar', tier: '三线' },
      { name: '通卡邦', nameEn: 'Tonekabon', tier: '三线' },
      { name: '博季努尔德', nameEn: 'Bojnurd', tier: '三线' },
      { name: '埃斯费赖恩', nameEn: 'Esfarayen', tier: '三线' },
      { name: '萨卜泽瓦尔', nameEn: 'Sabzevar', tier: '三线' },
      { name: '卡尚', nameEn: 'Kashan', tier: '三线' },
      { name: '纳坦兹', nameEn: 'Natanz', tier: '三线' },
      { name: '沙赫雷克尔德', nameEn: 'Shahrekord', tier: '三线' },
      { name: '博鲁杰尔德', nameEn: 'Borujerd', tier: '三线' },
      { name: '霍拉马巴德', nameEn: 'Khorramabad', tier: '三线' },
      { name: '伊拉姆', nameEn: 'Ilam', tier: '三线' },
      { name: '霍拉姆沙赫尔', nameEn: 'Khorramshahr', tier: '三线' },
      { name: '阿巴丹', nameEn: 'Abadan', tier: '三线' },
      { name: '马赫沙赫尔', nameEn: 'Mahshahr', tier: '三线' },
      { name: '巴姆', nameEn: 'Bam', tier: '三线' },
      { name: '比尔詹德', nameEn: 'Birjand', tier: '三线' },
      { name: '托尔巴特海达里耶', nameEn: 'Torbat-e Heydarieh', tier: '三线' },
      { name: '内沙布尔', nameEn: 'Neyshabur', tier: '三线' },
      { name: '托尔巴特贾姆', nameEn: 'Torbat-e Jam', tier: '三线' },
      { name: '泰耶巴德', nameEn: 'Taybad', tier: '三线' },
      { name: '萨拉赫斯', nameEn: 'Sarakhs', tier: '三线' },
      { name: '伊兹密尔', nameEn: 'Izmir', tier: '三线' },
      { name: '布尔萨', nameEn: 'Bursa', tier: '三线' },
      { name: '阿达纳', nameEn: 'Adana', tier: '三线' },
      { name: '加济安泰普', nameEn: 'Gaziantep', tier: '三线' },
      { name: '科尼亚', nameEn: 'Konya', tier: '三线' },
      { name: '安塔利亚', nameEn: 'Antalya', tier: '三线' },
      { name: '开塞利', nameEn: 'Kayseri', tier: '三线' },
      { name: '萨姆松', nameEn: 'Samsun', tier: '三线' },
      { name: '迪亚巴克尔', nameEn: 'Diyarbakir', tier: '三线' },
      { name: '梅尔辛', nameEn: 'Mersin', tier: '三线' },
      { name: '凡城', nameEn: 'Van', tier: '三线' },
      { name: '锡瓦斯', nameEn: 'Sivas', tier: '三线' },
      { name: '埃斯基谢希尔', nameEn: 'Eskisehir', tier: '三线' },
      { name: '代尼兹利', nameEn: 'Denizli', tier: '三线' },
      { name: '屈塔希亚', nameEn: 'Kutahya', tier: '三线' },
      { name: '马拉蒂亚', nameEn: 'Malatya', tier: '三线' },
      { name: '特拉布宗', nameEn: 'Trabzon', tier: '三线' },
      { name: '马尼萨', nameEn: 'Manisa', tier: '三线' },
      { name: '尚勒乌尔法', nameEn: 'Sanliurfa', tier: '三线' },
      { name: '巴利克西尔', nameEn: 'Balikesir', tier: '三线' },
      { name: '扎尔卡', nameEn: 'Zarqa', tier: '三线' },
      { name: '伊尔比德', nameEn: 'Irbid', tier: '三线' },
      { name: '亚喀巴', nameEn: 'Aqaba', tier: '三线' },
      { name: '马安', nameEn: 'Ma an', tier: '三线' },
      { name: '卡拉克', nameEn: 'Karak', tier: '三线' },
      { name: '塔菲拉', nameEn: 'Tafila', tier: '三线' },
      { name: '马德巴', nameEn: 'Madaba', tier: '三线' },
      { name: '杰拉什', nameEn: 'Jerash', tier: '三线' },
      { name: '拜勒加', nameEn: 'Balqa', tier: '三线' },
      { name: '阿杰隆', nameEn: 'Ajloun', tier: '三线' },
      { name: '马夫拉克', nameEn: 'Mafraq', tier: '三线' },
      { name: '的黎波里', nameEn: 'Tripoli', tier: '三线' },
      { name: '赛达', nameEn: 'Sidon', tier: '三线' },
      { name: '苏尔', nameEn: 'Tyre', tier: '三线' },
      { name: '扎赫勒', nameEn: 'Zahle', tier: '三线' },
      { name: '朱拜勒', nameEn: 'Byblos', tier: '三线' },
      { name: '巴贝克', nameEn: 'Baalbek', tier: '三线' },
      { name: '奈拜提耶', nameEn: 'Nabatieh', tier: '三线' },
      { name: '阿勒颇', nameEn: 'Aleppo', tier: '三线' },
      { name: '霍姆斯', nameEn: 'Homs', tier: '三线' },
      { name: '拉塔基亚', nameEn: 'Latakia', tier: '三线' },
      { name: '哈马', nameEn: 'Hama', tier: '三线' },
      { name: '代尔祖尔', nameEn: 'Deir ez-Zor', tier: '三线' },
      { name: '拉卡', nameEn: 'Raqqa', tier: '三线' },
      { name: '伊德利卜', nameEn: 'Idlib', tier: '三线' },
      { name: '德拉', nameEn: 'Daraa', tier: '三线' },
      { name: '苏韦达', nameEn: 'As-Suwayda', tier: '三线' },
      { name: '塔尔图斯', nameEn: 'Tartus', tier: '三线' },
      { name: '哈塞克', nameEn: 'Al-Hasakah', tier: '三线' },
      { name: '卡米什利', nameEn: 'Qamishli', tier: '三线' },
      { name: '曼比季', nameEn: 'Manbij', tier: '三线' },
      { name: '巴卜', nameEn: 'Al-Bab', tier: '三线' },
      { name: '阿扎兹', nameEn: 'Azaz', tier: '三线' },
      { name: '杰拉布卢斯', nameEn: 'Jarabulus', tier: '三线' },
      { name: '科巴尼', nameEn: 'Kobani', tier: '三线' },
      { name: '泰勒艾卜耶德', nameEn: 'Tell Abyad', tier: '三线' },
      { name: '拉斯艾因', nameEn: 'Ras al-Ayn', tier: '三线' },
      { name: '海法', nameEn: 'Haifa', tier: '三线' },
      { name: '里雄莱锡安', nameEn: 'Rishon LeZion', tier: '三线' },
      { name: '佩塔提克瓦', nameEn: 'Petah Tikva', tier: '三线' },
      { name: '阿什杜德', nameEn: 'Ashdod', tier: '三线' },
      { name: '内坦亚', nameEn: 'Netanya', tier: '三线' },
      { name: '贝尔谢巴', nameEn: 'Beersheba', tier: '三线' },
      { name: '霍隆', nameEn: 'Holon', tier: '三线' },
      { name: '贝内贝拉克', nameEn: 'Bnei Brak', tier: '三线' },
      { name: '拉马特甘', nameEn: 'Ramat Gan', tier: '三线' },
      { name: '阿什凯隆', nameEn: 'Ashkelon', tier: '三线' },
      { name: '巴特亚姆', nameEn: 'Bat Yam', tier: '三线' },
      { name: '雷霍沃特', nameEn: 'Rehovot', tier: '三线' },
      { name: '亚夫内', nameEn: 'Yavne', tier: '三线' },
      { name: '拉姆拉', nameEn: 'Ramla', tier: '三线' },
      { name: '洛德', nameEn: 'Lod', tier: '三线' },
      { name: '莫迪因马加比勒特', nameEn: 'Modiin-Maccabim-Reut', tier: '三线' },
      { name: '赫茨利亚', nameEn: 'Herzliya', tier: '三线' },
      { name: '卡法萨巴', nameEn: 'Kfar Saba', tier: '三线' },
      { name: '哈代拉', nameEn: 'Hadera', tier: '三线' },
      { name: '纳哈里亚', nameEn: 'Nahariya', tier: '三线' },
      { name: '阿克', nameEn: 'Acre', tier: '三线' },
      { name: '马阿洛特塔希哈', nameEn: 'Maalot-Tarshiha', tier: '三线' },
      { name: '卡尔米埃勒', nameEn: 'Karmiel', tier: '三线' },
      { name: '提比里亚', nameEn: 'Tiberias', tier: '三线' },
      { name: '卡茨林', nameEn: 'Katzrin', tier: '三线' },
      { name: '谢莫纳城', nameEn: 'Kiryat Shmona', tier: '三线' },
      { name: '阿拉德', nameEn: 'Arad', tier: '三线' },
      { name: '迪莫纳', nameEn: 'Dimona', tier: '三线' },
      { name: '奥法基姆', nameEn: 'Ofakim', tier: '三线' },
      { name: '内蒂沃特', nameEn: 'Netivot', tier: '三线' },
      { name: '埃拉特', nameEn: 'Eilat', tier: '三线' },
      { name: '汗尤尼斯', nameEn: 'Khan Yunis', tier: '三线' },
      { name: '拉法', nameEn: 'Rafah', tier: '三线' },
      { name: '希伯伦', nameEn: 'Hebron', tier: '三线' },
      { name: '纳布卢斯', nameEn: 'Nablus', tier: '三线' },
      { name: '杰宁', nameEn: 'Jenin', tier: '三线' },
      { name: '图勒凯尔姆', nameEn: 'Tulkarm', tier: '三线' },
      { name: '拉姆安拉', nameEn: 'Ramallah', tier: '三线' },
      { name: '伯利恒', nameEn: 'Bethlehem', tier: '三线' },
      { name: '杰里科', nameEn: 'Jericho', tier: '三线' },
      { name: '盖勒吉利耶', nameEn: 'Qalqilya', tier: '三线' },
      { name: '塔伊兹', nameEn: 'Taiz', tier: '三线' },
      { name: '荷台达', nameEn: 'Hodeidah', tier: '三线' },
      { name: '伊卜', nameEn: 'Ibb', tier: '三线' },
      { name: '扎马尔', nameEn: 'Dhamar', tier: '三线' },
      { name: '哈杰', nameEn: 'Hajjah', tier: '三线' },
      { name: '达利阿', nameEn: 'Dhale', tier: '三线' },
      { name: '贝达', nameEn: 'Al Bayda', tier: '三线' },
      { name: '马里卜', nameEn: 'Marib', tier: '三线' },
      { name: '哈德拉毛', nameEn: 'Hadhramaut', tier: '三线' },
      { name: '舍卜沃', nameEn: 'Shabwah', tier: '三线' },
      { name: '阿比扬', nameEn: 'Abyan', tier: '三线' },
      { name: '拉赫季', nameEn: 'Lahij', tier: '三线' },
    ],
  },
]

// 根据地区代码获取城市列表
export function getCitiesByRegion(regionCode: string): GeoCity[] {
  const region = GEO_REGIONS.find(r => r.code === regionCode || r.name === regionCode || r.nameEn === regionCode)
  return region?.cities || []
}

// 获取所有地区名称
export function getRegionNames(): string[] {
  return GEO_REGIONS.map(r => r.name)
}

// 获取默认GEO配置（中国和印度，及其所有城市）
export function getDefaultGeoConfig(): { geoRegion: string; geoCity: string } {
  const defaultRegions = ['中国', '印度']
  const defaultCities = [
    ...getCitiesByRegion('中国').map(c => c.name),
    ...getCitiesByRegion('印度').map(c => c.name),
  ]
  return {
    geoRegion: defaultRegions.join(','),
    geoCity: defaultCities.join(','),
  }
}
