/**
 * 接头四系列（I/B/G/O）的**手册基础订购号**清单（含中/英型式名）
 * ==========================================================================
 * ⚠️ 自动生成，勿手改。重新生成：`node scripts/_extract_conn_codes.js`
 *
 * 为什么用"枚举订购号"而不是"段位拼装"：手册对这四个系列**没有型号说明页**，
 *   只有「订购信息表」——逐行枚举基础订购号（本文件即那批行）。
 *   段位拼装会拼出手册里不存在的组合；枚举则每一条都是手册里真实存在的订购号。
 * 完整的订货号 = 材料代码（前缀） + 本文件的 code + 工艺规范代码（后缀）。
 */

export interface ConnCodeOption {
  /** 手册基础订购号（**不含**材料前缀与工艺规范后缀），如 `GJ-MR4-TB4-12` */
  code: string;
  /** 型式名（中文，手册订购信息表原文） */
  zh: string;
  /** 型式名（英文，站内数据自带） */
  en: string;
}

export const CONN_CODES: Record<string, ConnCodeOption[]> = {
  "B": [
    { code: "BC-TB10M", zh: "四通接头", en: "four-way connector" },
    { code: "BC-TB4", zh: "四通接头", en: "four-way connector" },
    { code: "BC-TB6", zh: "四通接头", en: "four-way connector" },
    { code: "BC-TB6M", zh: "四通接头", en: "four-way connector" },
    { code: "BC-TB8", zh: "四通接头", en: "four-way connector" },
    { code: "BE-TB10M", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB12", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB12M", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB18M", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB4", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB6", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB6M", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB8", zh: "90°弯头", en: "90° elbow" },
    { code: "BE-TB8M", zh: "90°弯头", en: "90° elbow" },
    { code: "BT-TB10M", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB10M-TB10M-TB6M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB10M-TB10M-TB8M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB12", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB12M", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB12M-TB12M-TB6M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB12M-TB12M-TB8M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB12-TB12-TB4", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB12-TB12-TB6", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB18M", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB4", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB6", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB6M", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB6-TB6-TB4", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB8", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB8M", zh: "三通接头", en: "three-way connector" },
    { code: "BT-TB8M-TB8M-TB6M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB8-TB8-TB4", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BT-TB8-TB8-TB6", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "BU-TB10M-TB6M", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB12M-TB10M", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB12M-TB6M", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB12M-TB8M", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB12-TB8", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB16-TB12", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB16-TB8", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB18M-TB12M", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB18M-TB6M", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB6-TB4", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB8-TB4", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BU-TB8-TB6", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "BWR-4", zh: "焊接环", en: "welding ring" },
    { code: "BWR-6", zh: "焊接环", en: "welding ring" },
    { code: "BWR-8", zh: "焊接环", en: "welding ring" },
  ],
  "G": [
    { code: "FLC-MR4", zh: "管接头锁定装置", en: "pipe joint locking device" },
    { code: "FLC-MR8", zh: "管接头锁定装置", en: "pipe joint locking device" },
    { code: "GA-FMR2-MR4", zh: "内外螺纹转换本体", en: "internal and external thread conversion body" },
    { code: "GA-FMR4-MR2", zh: "内外螺纹转换本体", en: "internal and external thread conversion body" },
    { code: "GA-FMR4-MR8", zh: "内外螺纹转换本体", en: "internal and external thread conversion body" },
    { code: "GA-FMR8-MR4", zh: "内外螺纹转换本体", en: "internal and external thread conversion body" },
    { code: "GC-MR12", zh: "四通本体", en: "four-way body" },
    { code: "GC-MR16", zh: "四通本体", en: "four-way body" },
    { code: "GC-MR2", zh: "四通本体", en: "four-way body" },
    { code: "GC-MR4", zh: "四通本体", en: "four-way body" },
    { code: "GC-MR8", zh: "四通本体", en: "four-way body" },
    { code: "GCP-FMR12", zh: "管帽", en: "pipe cap" },
    { code: "GCP-FMR16", zh: "管帽", en: "pipe cap" },
    { code: "GCP-FMR2", zh: "管帽", en: "pipe cap" },
    { code: "GCP-FMR4", zh: "管帽", en: "pipe cap" },
    { code: "GCP-FMR8", zh: "管帽", en: "pipe cap" },
    { code: "GE-HMR4", zh: "高流量连接-弯头本体", en: "High flow connection - elbow body" },
    { code: "GE-MR12", zh: "弯头本体", en: "elbow body" },
    { code: "GE-MR16", zh: "弯头本体", en: "elbow body" },
    { code: "GE-MR2", zh: "弯头本体", en: "elbow body" },
    { code: "GE-MR4", zh: "弯头本体", en: "elbow body" },
    { code: "GE-MR4-N2", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "GE-MR4-N4", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "GE-MR8", zh: "弯头本体", en: "elbow body" },
    { code: "GE-MR8-N6", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "GE-MR8-N8", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "GFC-FMR4-FMR2", zh: "内螺纹变径本体", en: "internal thread diameter reducing body" },
    { code: "GFC-FMR8-FMR4", zh: "内螺纹变径本体", en: "internal thread diameter reducing body" },
    { code: "GGB-MR12", zh: "盲垫片", en: "blind gasket" },
    { code: "GGB-MR16", zh: "盲垫片", en: "blind gasket" },
    { code: "GGB-MR2", zh: "盲垫片", en: "blind gasket" },
    { code: "GGB-MR4", zh: "盲垫片", en: "blind gasket" },
    { code: "GGB-MR8", zh: "盲垫片", en: "blind gasket" },
    { code: "GG-MR12", zh: "平垫片", en: "flat gasket" },
    { code: "GG-MR12-R", zh: "垫片支承组件", en: "gasket support assembly" },
    { code: "GG-MR16", zh: "平垫片", en: "flat gasket" },
    { code: "GG-MR16-R", zh: "垫片支承组件", en: "gasket support assembly" },
    { code: "GG-MR2", zh: "平垫片", en: "flat gasket" },
    { code: "GG-MR4", zh: "平垫片", en: "flat gasket" },
    { code: "GG-MR4-R", zh: "垫片支承组件", en: "gasket support assembly" },
    { code: "GG-MR8", zh: "平垫片", en: "flat gasket" },
    { code: "GG-MR8-R", zh: "垫片支承组件", en: "gasket support assembly" },
    { code: "GJB-MR12", zh: "盲接管", en: "blind takeover" },
    { code: "GJB-MR16", zh: "盲接管", en: "blind takeover" },
    { code: "GJB-MR2", zh: "盲接管", en: "blind takeover" },
    { code: "GJB-MR4", zh: "盲接管", en: "blind takeover" },
    { code: "GJB-MR8", zh: "盲接管", en: "blind takeover" },
    { code: "GJ-HMR4-TB6-0.60", zh: "高流量连接-对焊接管", en: "High Flow Connection - Pair Welded Pipe" },
    { code: "GJ-HMR4-TB6-1.19", zh: "高流量连接-对焊接管", en: "High Flow Connection - Pair Welded Pipe" },
    { code: "GJ-HMR4-TB6-1.31", zh: "高流量连接-对焊接管", en: "High Flow Connection - Pair Welded Pipe" },
    { code: "GJ-MR12-TB12", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR12-TB12-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR12-TB18M-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR12-TS12", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJ-MR16-TB16", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR16-TB16-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR16-TS16", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJ-MR2-TB2", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR2-TB2-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR2-TS1", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJ-MR2-TS2", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJ-MR4-TB2", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR4-TB4", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR4-TB4-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR4-TB4-4", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR4-TB4-6", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR4-TB6M-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR4-TB8M-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR4-TF4", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "GJ-MR4-TS2", zh: "变径插焊接管", en: "variable diameter insertion welded pipe" },
    { code: "GJ-MR4-TS4", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJ-MR8-TB10M-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB12M-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB4", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR8-TB4-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB6", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR8-TB6-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB6-4", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB8", zh: "管外焊接管", en: "external welded pipe" },
    { code: "GJ-MR8-TB8-12", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB8-4", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TB8-6", zh: "长对焊接管", en: "long pair welded pipe" },
    { code: "GJ-MR8-TF6", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "GJ-MR8-TF8", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "GJ-MR8-TS4", zh: "变径插焊接管", en: "variable diameter insertion welded pipe" },
    { code: "GJ-MR8-TS6", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJ-MR8-TS8", zh: "长插焊接管", en: "long insertion welded pipe" },
    { code: "GJS-MR12-TB18M-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR2-TB2-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TB2-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TB4-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TB4-4", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TB4-6", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TB6M-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TB8M-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR4-TS4-0.50", zh: "短插焊接管", en: "short-insertion welded pipe" },
    { code: "GJS-MR4-TS4-0.75", zh: "短插焊接管", en: "short-insertion welded pipe" },
    { code: "GJS-MR8-TB10M-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB12M-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB4-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB6-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB6-4", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB8-12", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB8-4", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJS-MR8-TB8-6", zh: "短对焊接管", en: "short pair welded pipe" },
    { code: "GJW-FMR4", zh: "可旋转焊接组件", en: "rotatable welding assembly" },
    { code: "GJW-FMR4-F4", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "GJW-FMR4-FN4", zh: "NPT内螺纹焊接组件", en: "NPT internal thread welding assembly" },
    { code: "GJW-FMR4-N2", zh: "NPT外螺纹焊接组件", en: "NPT external thread welding assembly" },
    { code: "GJW-FMR4-N4", zh: "NPT外螺纹焊接组件", en: "NPT external thread welding assembly" },
    { code: "GJW-FMR8", zh: "可旋转焊接组件", en: "rotatable welding assembly" },
    { code: "GJW-FMR8-F6", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "GJW-FMR8-F8", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "GJW-FMR8-FN6", zh: "NPT内螺纹焊接组件", en: "NPT internal thread welding assembly" },
    { code: "GJW-FMR8-FN8", zh: "NPT内螺纹焊接组件", en: "NPT internal thread welding assembly" },
    { code: "GJW-FMR8-N6", zh: "NPT外螺纹焊接组件", en: "NPT external thread welding assembly" },
    { code: "GJW-FMR8-N8", zh: "NPT外螺纹焊接组件", en: "NPT external thread welding assembly" },
    { code: "GMN-HMR4", zh: "高流量连接-外螺纹螺母", en: "High flow connection - external threaded nut" },
    { code: "GMN-MR12", zh: "外螺纹螺母", en: "external thread nut" },
    { code: "GMN-MR16", zh: "外螺纹螺母", en: "external thread nut" },
    { code: "GMN-MR2", zh: "外螺纹螺母", en: "external thread nut" },
    { code: "GMN-MR4", zh: "外螺纹螺母", en: "external thread nut" },
    { code: "GMN-MR4-0.54", zh: "短外螺纹螺母", en: "short external thread nut" },
    { code: "GMN-MR4-0.65", zh: "短外螺纹螺母", en: "short external thread nut" },
    { code: "GMN-MR8", zh: "外螺纹螺母", en: "external thread nut" },
    { code: "GN-FMR12", zh: "内螺纹螺母", en: "internal thread nut" },
    { code: "GN-FMR16", zh: "内螺纹螺母", en: "internal thread nut" },
    { code: "GN-FMR2", zh: "内螺纹螺母", en: "internal thread nut" },
    { code: "GN-FMR4", zh: "内螺纹螺母", en: "internal thread nut" },
    { code: "GN-FMR8", zh: "内螺纹螺母", en: "internal thread nut" },
    { code: "GN-HMR4-11.7", zh: "高流量连接-内螺纹螺母", en: "High Flow Connection - Internal Thread Nut" },
    { code: "GN-HMR4-9.9", zh: "高流量连接-内螺纹螺母", en: "High Flow Connection - Internal Thread Nut" },
    { code: "GP-MR12", zh: "堵头", en: "plug" },
    { code: "GP-MR16", zh: "堵头", en: "plug" },
    { code: "GP-MR2", zh: "堵头", en: "plug" },
    { code: "GP-MR4", zh: "堵头", en: "plug" },
    { code: "GP-MR8", zh: "堵头", en: "plug" },
    { code: "GT-HMR4", zh: "高流量连接-三通本体", en: "High-traffic connection - three-way body" },
    { code: "GT-MR12", zh: "三通本体", en: "three-way body" },
    { code: "GT-MR16", zh: "三通本体", en: "three-way body" },
    { code: "GT-MR2", zh: "三通本体", en: "three-way body" },
    { code: "GT-MR4", zh: "三通本体", en: "three-way body" },
    { code: "GT-MR8", zh: "三通本体", en: "three-way body" },
    { code: "GUB-HMR4-TB6", zh: "高流量连接-穿板管对焊本体", en: "High-flow connection-through-plate pipe butt welding body" },
    { code: "GUB-MR4", zh: "穿板直通本体", en: "through-plate through-body" },
    { code: "GUB-MR4-F4", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "GUB-MR4-N4", zh: "穿板外螺纹本体", en: "through plate external thread body" },
    { code: "GUB-MR4-TB4", zh: "对焊穿板连接本体", en: "connecting body to welded-through plate" },
    { code: "GUB-MR8", zh: "穿板直通本体", en: "through-plate through-body" },
    { code: "GUB-MR8-F6", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "GUB-MR8-F8", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "GUB-MR8-N4", zh: "穿板外螺纹本体", en: "through plate external thread body" },
    { code: "GU-HMR4-TB6", zh: "高流量连接-对焊本体", en: "High-flow connection-butt welding body" },
    { code: "GU-MR12", zh: "直通本体", en: "through body" },
    { code: "GU-MR12-FN12", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR12-N12", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR16", zh: "直通本体", en: "through body" },
    { code: "GU-MR16-FN16", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR16-N16", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR2", zh: "直通本体", en: "through body" },
    { code: "GU-MR2-FN1", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR2-FN2", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR2-N1", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR2-N2", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR4", zh: "直通本体", en: "through body" },
    { code: "GU-MR4-F2", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "GU-MR4-F4", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "GU-MR4-FN2", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR4-FN4", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR4-MR2", zh: "变径直通本体", en: "variable diameter straight-through body" },
    { code: "GU-MR4-N2", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR4-N4", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR4-ST9", zh: "直螺纹O形圈密封外螺纹本体", en: "Straight thread O-ring sealing external thread body" },
    { code: "GU-MR8", zh: "直通本体", en: "through body" },
    { code: "GU-MR8-F6", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "GU-MR8-F8", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "GU-MR8-FN6", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR8-FN8", zh: "NPT内螺纹本体", en: "NPT internal thread body" },
    { code: "GU-MR8-MR4", zh: "变径直通本体", en: "variable diameter straight-through body" },
    { code: "GU-MR8-N4", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR8-N6", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR8-N8", zh: "NPT外螺纹本体", en: "NPT external thread body" },
    { code: "GU-MR8-ST14", zh: "直螺纹O形圈密封外螺纹本体", en: "Straight thread O-ring sealing external thread body" },
    { code: "GU-MR8-ST9", zh: "直螺纹O形圈密封外螺纹本体", en: "Straight thread O-ring sealing external thread body" },
  ],
  "I": [
    { code: "IC-TB10M", zh: "四通接头", en: "four-way connector" },
    { code: "IC-TB12M", zh: "四通接头", en: "four-way connector" },
    { code: "IC-TB2", zh: "四通接头", en: "four-way connector" },
    { code: "IC-TB4", zh: "四通接头", en: "four-way connector" },
    { code: "IC-TB6", zh: "四通接头", en: "four-way connector" },
    { code: "IC-TB6M", zh: "四通接头", en: "four-way connector" },
    { code: "IC-TB8", zh: "四通接头", en: "four-way connector" },
    { code: "ID-TB4", zh: "立体三通", en: "three-dimensional tee" },
    { code: "ID-TB6", zh: "立体三通", en: "three-dimensional tee" },
    { code: "ID-TB6M", zh: "立体三通", en: "three-dimensional tee" },
    { code: "ID-TB8", zh: "立体三通", en: "three-dimensional tee" },
    { code: "IE-TB10M", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB10M-TB6M", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IE-TB12M", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB12M-TB6M", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IE-TB12M-TB8M", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IE-TB2", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB4", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB6", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB6M", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB6-TB4", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IE-TB8", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB8M", zh: "90°弯头", en: "90° elbow" },
    { code: "IE-TB8M-TB6M", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IE-TB8-TB4", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IE-TB8-TB6", zh: "变径90°弯头", en: "Diameter change 90° elbow" },
    { code: "IT-TB10M", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB10M-TB10M-TB6M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "IT-TB12M", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB12M-TB12M-TB6M", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "IT-TB2", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB4", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB4-25", zh: "直通端加长三通接头", en: "straight-through end extended three-way connector" },
    { code: "IT-TB4-45", zh: "分支端加长三通接头", en: "branch end extended three-way connector" },
    { code: "IT-TB6", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB6M", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB6-TB6-TB4", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "IT-TB8", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB8M", zh: "三通接头", en: "three-way connector" },
    { code: "IT-TB8-TB8-TB4", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "IT-TB8-TB8-TB6", zh: "变径三通接头", en: "variable diameter three-way connector" },
    { code: "IU-TB4-TB2", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "IU-TB6-TB4", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "IU-TB8-TB4", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "IU-TB8-TB6", zh: "变径直通接头", en: "variable diameter through joint" },
    { code: "IV-TB4", zh: "45°弯头", en: "45° elbow" },
    { code: "IV-TB6", zh: "45°弯头", en: "45° elbow" },
    { code: "IV-TB8", zh: "45°弯头", en: "45° elbow" },
  ],
  "O": [
    { code: "OBU-OR4", zh: "穿板直通本体", en: "through-plate through-body" },
    { code: "OBU-OR8", zh: "穿板直通本体", en: "through-plate through-body" },
    { code: "OE-OR12", zh: "弯头本体", en: "elbow body" },
    { code: "OE-OR12-F12", zh: "卡套连接弯头本体", en: "sleeve connecting elbow body" },
    { code: "OE-OR12-N12", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "OE-OR12-ST17P", zh: "可调弯头本体", en: "adjustable elbow body" },
    { code: "OE-OR16", zh: "弯头本体", en: "elbow body" },
    { code: "OE-OR16-F16", zh: "卡套连接弯头本体", en: "sleeve connecting elbow body" },
    { code: "OE-OR16-N16", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "OE-OR16-ST21P", zh: "可调弯头本体", en: "adjustable elbow body" },
    { code: "OE-OR4", zh: "弯头本体", en: "elbow body" },
    { code: "OE-OR4-F4", zh: "卡套连接弯头本体", en: "sleeve connecting elbow body" },
    { code: "OE-OR4-N2", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "OE-OR4-N4", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "OE-OR4-ST7P", zh: "可调弯头本体", en: "adjustable elbow body" },
    { code: "OE-OR8", zh: "弯头本体", en: "elbow body" },
    { code: "OE-OR8-F6", zh: "卡套连接弯头本体", en: "sleeve connecting elbow body" },
    { code: "OE-OR8-F8", zh: "卡套连接弯头本体", en: "sleeve connecting elbow body" },
    { code: "OE-OR8-N6", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "OE-OR8-N8", zh: "NPT 外螺纹弯头本体", en: "NPT external thread elbow body" },
    { code: "OE-OR8-ST12P", zh: "可调弯头本体", en: "adjustable elbow body" },
    { code: "OE-OR8-ST9P", zh: "可调弯头本体", en: "adjustable elbow body" },
    { code: "OJ-OR12-TB12A", zh: "自动卡套管焊接接管", en: "automatic clamping sleeve welding joint" },
    { code: "OJ-OR12-TF12", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "OJ-OR12-TS12", zh: "插焊接管", en: "insertion welding pipe" },
    { code: "OJ-OR16-TB16A", zh: "自动卡套管焊接接管", en: "automatic clamping sleeve welding joint" },
    { code: "OJ-OR16-TF16", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "OJ-OR16-TS16", zh: "插焊接管", en: "insertion welding pipe" },
    { code: "OJ-OR2-TS2", zh: "插焊接管", en: "insertion welding pipe" },
    { code: "OJ-OR4-TB2", zh: "对焊接管", en: "double welded pipe" },
    { code: "OJ-OR4-TB4", zh: "对焊接管", en: "double welded pipe" },
    { code: "OJ-OR4-TB4A", zh: "自动卡套管焊接接管", en: "automatic clamping sleeve welding joint" },
    { code: "OJ-OR4-TF4", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "OJ-OR4-TS2", zh: "变径插焊接管", en: "variable diameter insertion welded pipe" },
    { code: "OJ-OR4-TS4", zh: "插焊接管", en: "insertion welding pipe" },
    { code: "OJ-OR6-TS6", zh: "插焊接管", en: "insertion welding pipe" },
    { code: "OJ-OR8-TB4", zh: "对焊接管", en: "double welded pipe" },
    { code: "OJ-OR8-TB6", zh: "对焊接管", en: "double welded pipe" },
    { code: "OJ-OR8-TB6A", zh: "自动卡套管焊接接管", en: "automatic clamping sleeve welding joint" },
    { code: "OJ-OR8-TB8", zh: "对焊接管", en: "double welded pipe" },
    { code: "OJ-OR8-TB8A", zh: "自动卡套管焊接接管", en: "automatic clamping sleeve welding joint" },
    { code: "OJ-OR8-TF6", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "OJ-OR8-TF8", zh: "卡套管接管", en: "Cartridge tube connector" },
    { code: "OJ-OR8-TS4", zh: "变径插焊接管", en: "variable diameter insertion welded pipe" },
    { code: "OJ-OR8-TS8", zh: "插焊接管", en: "insertion welding pipe" },
    { code: "OJW-FOR12-F12", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "OJW-FOR12-FN12", zh: "NPT 内螺纹焊接组件", en: "NPT Internal Thread Weld Assembly" },
    { code: "OJW-FOR12-N12", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR12-ST17", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR16-F16", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "OJW-FOR16-FN16", zh: "NPT 内螺纹焊接组件", en: "NPT Internal Thread Weld Assembly" },
    { code: "OJW-FOR16-N16", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR16-ST21", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR4", zh: "可旋转焊接组件", en: "rotatable welding assembly" },
    { code: "OJW-FOR4-F4", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "OJW-FOR4-FN4", zh: "NPT 内螺纹焊接组件", en: "NPT Internal Thread Weld Assembly" },
    { code: "OJW-FOR4-N4", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR4-ST7", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR8", zh: "可旋转焊接组件", en: "rotatable welding assembly" },
    { code: "OJW-FOR8-F6", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "OJW-FOR8-F8", zh: "卡套连接焊接组件", en: "sleeve connection welding assembly" },
    { code: "OJW-FOR8-FN6", zh: "NPT 内螺纹焊接组件", en: "NPT Internal Thread Weld Assembly" },
    { code: "OJW-FOR8-FN8", zh: "NPT 内螺纹焊接组件", en: "NPT Internal Thread Weld Assembly" },
    { code: "OJW-FOR8-N6", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR8-N8", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR8-ST12", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "OJW-FOR8-ST9", zh: "NPT 外螺纹焊接组件", en: "NPT External Thread Weld Assembly" },
    { code: "ON-FOR12", zh: "盲螺母", en: "blind nut" },
    { code: "ON-FOR12-B", zh: "盲螺母", en: "blind nut" },
    { code: "ON-FOR16", zh: "盲螺母", en: "blind nut" },
    { code: "ON-FOR4", zh: "盲螺母", en: "blind nut" },
    { code: "ON-FOR4-B", zh: "盲螺母", en: "blind nut" },
    { code: "ON-FOR8", zh: "盲螺母", en: "blind nut" },
    { code: "ON-FOR8-B", zh: "盲螺母", en: "blind nut" },
    { code: "OP-OR12", zh: "堵头", en: "plug" },
    { code: "OP-OR16", zh: "堵头", en: "plug" },
    { code: "OP-OR4", zh: "堵头", en: "plug" },
    { code: "OP-OR8", zh: "堵头", en: "plug" },
    { code: "OR-010", zh: "O 形圈", en: "O-ring" },
    { code: "OR-111", zh: "O 形圈", en: "O-ring" },
    { code: "OR-116", zh: "O 形圈", en: "O-ring" },
    { code: "OR-215", zh: "O 形圈", en: "O-ring" },
    { code: "OT-OR12", zh: "三通本体", en: "three-way body" },
    { code: "OT-OR16", zh: "三通本体", en: "three-way body" },
    { code: "OT-OR4", zh: "三通本体", en: "three-way body" },
    { code: "OT-OR8", zh: "三通本体", en: "three-way body" },
    { code: "OUB-OR12-F12", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "OUB-OR16-F16", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "OUB-OR4-F4", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "OUB-OR8-F6", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "OUB-OR8-F8", zh: "穿板卡套连接本体", en: "Through-plate card sleeve connecting body" },
    { code: "OU-OR12-F12", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "OU-OR12-FN12", zh: "NPT 内螺纹本体", en: "NPT internal thread body" },
    { code: "OU-OR12-N12", zh: "NPT 外螺纹本体", en: "NPT external thread body" },
    { code: "OU-OR12-ST17", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR12-TB12A", zh: "自动卡套管焊接本体", en: "automatic clamping sleeve welding body" },
    { code: "OU-OR12-TS12", zh: "承插焊连接本体", en: "socket welding connecting body" },
    { code: "OU-OR16-F16", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "OU-OR16-FN16", zh: "NPT 内螺纹本体", en: "NPT internal thread body" },
    { code: "OU-OR16-N16", zh: "NPT 外螺纹本体", en: "NPT external thread body" },
    { code: "OU-OR16-ST21", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR16-TB16A", zh: "自动卡套管焊接本体", en: "automatic clamping sleeve welding body" },
    { code: "OU-OR16-TS16", zh: "承插焊连接本体", en: "socket welding connecting body" },
    { code: "OU-OR4", zh: "直通本体", en: "through body" },
    { code: "OU-OR4-F2", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "OU-OR4-F4", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "OU-OR4-FN2", zh: "NPT 内螺纹本体", en: "NPT internal thread body" },
    { code: "OU-OR4-FN4", zh: "NPT 内螺纹本体", en: "NPT internal thread body" },
    { code: "OU-OR4-N2", zh: "NPT 外螺纹本体", en: "NPT external thread body" },
    { code: "OU-OR4-N4", zh: "NPT 外螺纹本体", en: "NPT external thread body" },
    { code: "OU-OR4-ST7", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR4-ST9", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR4-TB4A", zh: "自动卡套管焊接本体", en: "automatic clamping sleeve welding body" },
    { code: "OU-OR4-TS2", zh: "承插焊连接本体", en: "socket welding connecting body" },
    { code: "OU-OR4-TS4", zh: "承插焊连接本体", en: "socket welding connecting body" },
    { code: "OU-OR8", zh: "直通本体", en: "through body" },
    { code: "OU-OR8-F6", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "OU-OR8-F8", zh: "卡套连接本体", en: "Cartridge sleeve connection body" },
    { code: "OU-OR8-FN6", zh: "NPT 内螺纹本体", en: "NPT internal thread body" },
    { code: "OU-OR8-FN8", zh: "NPT 内螺纹本体", en: "NPT internal thread body" },
    { code: "OU-OR8-N6", zh: "NPT 外螺纹本体", en: "NPT external thread body" },
    { code: "OU-OR8-N8", zh: "NPT 外螺纹本体", en: "NPT external thread body" },
    { code: "OU-OR8-OR4", zh: "直通本体", en: "through body" },
    { code: "OU-OR8-ST12", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR8-ST7", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR8-ST9", zh: "直螺纹 O 形圈密封", en: "Straight threaded O-ring seal" },
    { code: "OU-OR8-TB6A", zh: "自动卡套管焊接本体", en: "automatic clamping sleeve welding body" },
    { code: "OU-OR8-TB8A", zh: "自动卡套管焊接本体", en: "automatic clamping sleeve welding body" },
    { code: "OU-OR8-TS6", zh: "承插焊连接本体", en: "socket welding connecting body" },
    { code: "OU-OR8-TS8", zh: "承插焊连接本体", en: "socket welding connecting body" },
  ],
};
