// VALTRIX 产品数据 - 三层结构：Tab 大分类 → Category 子分类 → Model 具体型号
// 自动生成于 2026-09-09T14:46:17.582Z，数据源：芯阀科技官网

export interface ProductSpec {
  label: string;
  value: string;
  labelEn?: string;
  valueEn?: string;
}

export interface ProductModel {
  id: string;
  name: string;
  nameEn?: string;
  nameJa?: string;
  nameKo?: string;
  nameFr?: string;
  nameAr?: string;
  model: string;
  image: string;
  images?: string[];
  description: string;
  descriptionEn?: string;
  specs: ProductSpec[];
  purchaseMode?: string;
  shopSlug?: string;
  frames360?: { path: string; count: number; startIndex?: number };
  detailContent?: string;
  detailContentEn?: string;
  features?: string[];
  featuresEn?: string[];
  manualUrl?: string;
  manualUrlEn?: string;
  subtitle?: string;
  subtitleEn?: string;
  summary?: string;
  summaryEn?: string;
}

export interface ProductCategory {
  id: string;
  name: string;
  nameEn?: string;
  nameJa?: string;
  nameKo?: string;
  nameFr?: string;
  nameAr?: string;
  icon?: string;
  description?: string;
  descriptionEn?: string;
  models: ProductModel[];
}

export interface ProductTab {
  id: string;
  name: string;
  nameEn?: string;
  nameJa?: string;
  nameKo?: string;
  nameFr?: string;
  nameAr?: string;
  purchaseMode?: string;
  categories: ProductCategory[];
}

export const productTabs: ProductTab[] = [
  {
    id: 'fittings',
    name: '接头',
    nameEn: 'Fittings',
    nameJa: '継手',
    nameKo: '피팅',
    nameFr: 'Raccords',
    nameAr: 'التوصيلات',
    purchaseMode: 'quote',
    categories: [
      {
        id: 'face-seal',
        name: '面密封接头',
        nameEn: 'surface sealing joint',
        nameJa: 'フェースシールジョイント',
        nameKo: '면 밀봉 조인트',
        nameFr: 'Joint d\'étanchéité face',
        nameAr: 'وجه ختم المشترك',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'metal-face-seal-g-series',
            name: '金属面密封接头 G系列',
            nameEn: 'Metal Face Sealing Joint G Series',
            nameJa: '金属面シール継手 Gシリーズ',
            nameKo: '금속 표면 밀봉 조인트 G 시리즈',
            nameFr: 'Joint d\'étanchéité de surface métallique série G',
            nameAr: 'موصل ختم الوجه المعدني سلسلة G',
            model: '金属面密封接头 G',
            image: '/uploads/products/xinval/face-seal_metal-face-seal-g-series_1.jpg',
            images: ["/uploads/products/xinval/face-seal_metal-face-seal-g-series_1.jpg"],
            description: '芯阀 G 系列金属面密封接头，金属对金属密封，在真空到高压范围内提供无泄漏服务。',
            descriptionEn: 'Core Valve G Series Metal Face Seal Fittings, metal to metal seal, providing leak-free service over the vacuum to high pressure range.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'o-ring-face-seal-o-series',
            name: 'O形圈面密封接头 O系列',
            nameEn: 'O-ring surface sealing joint O series',
            nameJa: 'Oリング面シール継手Oシリーズ',
            nameKo: 'O-링 표면 밀봉 조인트 O 시리즈',
            nameFr: 'Joint d\'étanchéité de surface torique série O',
            nameAr: 'مفصل ختم سطح الحلقة O سلسلة O',
            model: 'O形圈面密封接头 O',
            image: '/uploads/products/xinval/face-seal_o-ring-face-seal-o-series_1.jpg',
            images: ["/uploads/products/xinval/face-seal_o-ring-face-seal-o-series_1.jpg"],
            description: '芯阀 O 系列 O 形圈面密封接头，保证从真空到高压的完美密封，易于安装和维护。',
            descriptionEn: 'Core valve O-series O-ring seal connectors ensure perfect sealing from vacuum to high pressure, and are easy to install and maintain.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'welded',
        name: '焊接接头',
        nameEn: 'welded joint',
        nameJa: '溶接ジョイント',
        nameKo: '용접 조인트',
        nameFr: 'Joints soudés',
        nameAr: 'وصلات ملحومة',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'micro-welded-i-series',
            name: '微焊接接头 I系列',
            nameEn: 'Microwelded Joints I Series',
            nameJa: 'マイクロ溶接継手Iシリーズ',
            nameKo: '마이크로 용접 조인트 I 시리즈',
            nameFr: 'Joints micro-soudés série I',
            nameAr: 'وصلات ملحومة دقيقة من سلسلة I',
            model: '微焊接接头 I',
            image: '/uploads/products/xinval/welded_micro-welded-i-series_1.jpg',
            images: ["/uploads/products/xinval/welded_micro-welded-i-series_1.jpg"],
            description: '芯阀微焊接接头适用于小型的焊接管道系统，满足多种应用需求。',
            descriptionEn: 'Core valve micro-welded joints are suitable for small welded piping systems to meet a variety of application needs.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'long-welded-b-series',
            name: '长焊接接头 B系列',
            nameEn: 'Long Weld Joint B Series',
            nameJa: 'ロング溶接継手 Bシリーズ',
            nameKo: '긴 용접 조인트 B 시리즈',
            nameFr: 'Joint soudé long série B',
            nameAr: 'المفاصل الملحومة الطويلة من السلسلة B',
            model: '长焊接接头 B',
            image: '/uploads/products/xinval/welded_long-welded-b-series_1.jpg',
            images: ["/uploads/products/xinval/welded_long-welded-b-series_1.jpg"],
            description: '芯阀长焊接接头采用延长的管设计，弯头通道圆弧连接，确保流体平稳流动。',
            descriptionEn: 'The long welded joint of the core valve adopts an extended tube design, and the elbow channel is connected in a circular arc to ensure the smooth flow of fluid.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'two-ferrule',
        name: '双卡套接头',
        nameEn: 'Twin Ferrule Fitting',
        nameJa: 'ツインフェルール継手',
        nameKo: '트윈 페룰 피팅',
        nameFr: 'Raccord à double ferrule',
        nameAr: 'وصلة فيرول مزدوجة',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'two-ferrule-fittings',
            name: '双卡套接头',
            nameEn: 'Twin Ferrule Fitting',
            nameJa: 'ツインフェルール継手',
            nameKo: '트윈 페룰 피팅',
            nameFr: 'Raccord à double ferrule',
            nameAr: 'وصلة فيرول مزدوجة',
            model: '双卡套接头',
            image: '/uploads/products/xinval/two-ferrule_two-ferrule-fittings_1.jpg',
            images: ["/uploads/products/xinval/two-ferrule_two-ferrule-fittings_1.jpg"],
            description: '芯阀双卡套接头采用各种外力反复作用及各种环境的变化与试炼，经过反复多次的装卸，确保产品质量。',
            descriptionEn: 'The core valve double card sleeve joint is subjected to various external forces and environmental changes and trials, and undergoes repeated loading and unloading to ensure product quality.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'threaded',
        name: '螺纹接头',
        nameEn: 'threaded joint',
        nameJa: 'ねじ継手',
        nameKo: '스레드 조인트',
        nameFr: 'Joint fileté',
        nameAr: 'مفصل ملولب',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'threaded-fittings',
            name: '螺纹接头',
            nameEn: 'threaded joint',
            nameJa: 'ねじ継手',
            nameKo: '스레드 조인트',
            nameFr: 'Joint fileté',
            nameAr: 'مفصل ملولب',
            model: '螺纹接头',
            image: '/uploads/products/xinval/threaded_threaded-fittings_1.jpg',
            images: ["/uploads/products/xinval/threaded_threaded-fittings_1.jpg"],
            description: '螺纹接头是流体系统中常见的一种连接方式，它通过螺纹将阀门与管道或其他阀体连接起来，其安装方便、成本效益高，并且适用于多种不同的管径和流体类型，广泛应用于流体控制系统中。',
            descriptionEn: 'Threaded connectors are a common connection method in fluid systems. They connect valves to pipes or other valve bodies through threads. They are easy to install, cost-effective, and suitable for various pipe diameters and fluid types, and are widely used in fluid control systems.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
    ],
  },
  {
    id: 'valves',
    name: '阀门',
    nameEn: 'Valves',
    nameJa: 'バルブ',
    nameKo: '밸브',
    nameFr: 'Vannes',
    nameAr: 'الصمامات',
    purchaseMode: 'quote',
    categories: [
      {
        id: 'diaphragm-valve',
        name: '隔膜阀',
        nameEn: 'diaphragm valve',
        nameJa: 'ダイヤフラム弁',
        nameKo: '다이어프램 밸브',
        nameFr: 'vanne à membrane',
        nameAr: 'صمام الحجاب الحاجز',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'ald-diaphragm-valve',
            name: '原子层沉积隔膜阀 ALD系列',
            nameEn: 'Atomic layer deposition diaphragm valve ALD series',
            nameJa: '原子層堆積ダイヤフラムバルブ ALD シリーズ',
            nameKo: '원자층 증착 다이어프램 밸브 ALD 시리즈',
            nameFr: 'Vanne à membrane de dépôt de couche atomique série ALD',
            nameAr: 'صمام الحجاب الحاجز لترسيب الطبقة الذرية سلسلة ALD',
            model: 'ALD',
            image: '/uploads/products/xinval/diaphragm-valve_ald-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_ald-diaphragm-valve_1.jpg"],
            description: '我们提供的先进 ALD 阀门技术，具有超高高循环寿命，提高芯片生产效率。',
            descriptionEn: 'We offer advanced ALD valve technology with ultra-long cycle life, improving chip production efficiency.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv1-diaphragm-valve',
            name: '低压小流量隔膜阀 DV1系列',
            nameEn: 'Low Pressure Small Flow Diaphragm Valve DV1 Series',
            nameJa: '低圧小流量ダイヤフラムバルブ DV1シリーズ',
            nameKo: '저압 소유량 다이어프램 밸브 DV1 시리즈',
            nameFr: 'Vanne à membrane basse pression et faible débit série DV1',
            nameAr: 'صمام الحجاب الحاجز ذو الضغط المنخفض والتدفق الصغير سلسلة DV1',
            model: 'DV1',
            image: '/uploads/products/xinval/diaphragm-valve_dv1-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv1-diaphragm-valve_1.jpg"],
            description: 'DV1 系列低压小流量隔膜阀采用全封闭阀座设计，无泄漏。',
            descriptionEn: 'The DV1 series low-pressure, low-flow diaphragm valves feature a fully enclosed valve seat design, ensuring no leakage.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv2-diaphragm-valve',
            name: '低压中流量隔膜阀 DV2系列',
            nameEn: 'Low pressure medium flow diaphragm valve DV2 series',
            nameJa: '低圧中流量ダイヤフラムバルブ DV2シリーズ',
            nameKo: '저압 중유량 다이어프램 밸브 DV2 시리즈',
            nameFr: 'Vanne à membrane basse pression et moyen débit série DV2',
            nameAr: 'صمام الحجاب الحاجز ذو الضغط المنخفض والتدفق المتوسط سلسلة DV2',
            model: 'DV2',
            image: '/uploads/products/xinval/diaphragm-valve_dv2-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv2-diaphragm-valve_1.jpg"],
            description: 'DV2 系列低压中流量隔膜阀采用全封闭阀座设计，具有优越的抗膨胀和防污染能力。',
            descriptionEn: 'The DV2 series low-pressure medium-flow diaphragm valves adopt a fully enclosed valve seat design, which has superior anti-expansion and anti-contamination capabilities.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv3-diaphragm-valve',
            name: '低压大流量隔膜阀 DV3系列',
            nameEn: 'Low Pressure High Flow Diaphragm Valve DV3 Series',
            nameJa: '低圧大流量ダイヤフラムバルブ DV3シリーズ',
            nameKo: '저압 대유량 다이어프램 밸브 DV3 시리즈',
            nameFr: 'Vanne à membrane basse pression et grand débit série DV3',
            nameAr: 'صمام الحجاب الحاجز ذو الضغط المنخفض والتدفق الكبير سلسلة DV3',
            model: 'DV3',
            image: '/uploads/products/xinval/diaphragm-valve_dv3-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv3-diaphragm-valve_1.jpg"],
            description: 'DV3 系列低压大流量隔膜阀内部无螺纹和弹簧，减少颗粒生成和残留。',
            descriptionEn: 'The DV3 series low-pressure, high-flow diaphragm valves are internally thread-free and spring-free, reducing particle formation and residue.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv4-diaphragm-valve',
            name: '高压小流量隔膜阀 DV4系列',
            nameEn: 'High-pressure low-flow diaphragm valve DV4 series',
            nameJa: '高圧小流量ダイヤフラムバルブ DV4シリーズ',
            nameKo: '고압 소유량 다이어프램 밸브 DV4 시리즈',
            nameFr: 'Vanne à membrane haute pression et faible débit série DV4',
            nameAr: 'صمام الحجاب الحاجز ذو الضغط العالي والتدفق الصغير سلسلة DV4',
            model: 'DV4',
            image: '/uploads/products/xinval/diaphragm-valve_dv4-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv4-diaphragm-valve_1.jpg"],
            description: 'DV4 系列高压小流量隔膜阀内部无螺纹和弹簧，可完全清扫流道。',
            descriptionEn: 'The DV4 Series High Pressure Low Flow Diaphragm Valve has no internal threads or springs, allowing for complete cleaning of the flow channel.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv5-diaphragm-valve',
            name: '高压中流量隔膜阀 DV5系列',
            nameEn: 'High pressure medium flow diaphragm valve DV5 series',
            nameJa: '高圧中流量ダイヤフラムバルブ DV5シリーズ',
            nameKo: '고압 중유량 다이어프램 밸브 DV5 시리즈',
            nameFr: 'Vanne à membrane haute pression et moyen débit série DV5',
            nameAr: 'صمام الحجاب الحاجز ذو الضغط العالي والتدفق المتوسط سلسلة DV5',
            model: 'DV5',
            image: '/uploads/products/xinval/diaphragm-valve_dv5-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv5-diaphragm-valve_1.jpg"],
            description: 'DV5 系列高压中流量隔膜阀钴镍合金隔膜强度高、耐腐蚀，使用寿命长。',
            descriptionEn: 'The DV5 series high-pressure medium-flow diaphragm valves feature cobalt-nickel alloy diaphragms with high strength, corrosion resistance, and long service life.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv6-diaphragm-valve',
            name: '中压中流量隔膜阀 DV6系列',
            nameEn: 'Medium pressure medium flow diaphragm valve DV6 series',
            nameJa: '中圧中流量ダイヤフラムバルブ DV6シリーズ',
            nameKo: '중압 중유량 다이어프램 밸브 DV6 시리즈',
            nameFr: 'Vanne à membrane à moyenne pression et débit moyen série DV6',
            nameAr: 'صمام الحجاب الحاجز ذو الضغط المتوسط والتدفق المتوسط سلسلة DV6',
            model: 'DV6',
            image: '/uploads/products/xinval/diaphragm-valve_dv6-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv6-diaphragm-valve_1.jpg"],
            description: 'DV6 系列中压中流量隔膜阀钴镍合金隔膜强度高、耐腐蚀，使用寿命长。',
            descriptionEn: 'The DV6 series medium-pressure and medium-flow diaphragm valves feature cobalt-nickel alloy diaphragms with high strength, corrosion resistance, and long service life.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'dv7-diaphragm-valve',
            name: '高压弹簧隔膜阀 DV7系列',
            nameEn: 'High-pressure spring diaphragm valve DV7 series',
            nameJa: '高圧スプリングダイヤフラムバルブ DV7シリーズ',
            nameKo: '고압 스프링 다이어프램 밸브 DV7 시리즈',
            nameFr: 'Vanne à membrane à ressort haute pression série DV7',
            nameAr: 'صمام الحجاب الحاجز الزنبركي عالي الضغط سلسلة DV7',
            model: 'DV7',
            image: '/uploads/products/xinval/diaphragm-valve_dv7-diaphragm-valve_1.jpg',
            images: ["/uploads/products/xinval/diaphragm-valve_dv7-diaphragm-valve_1.jpg"],
            description: 'DV7 系列高压弹簧隔膜阀阀杆带弹簧复位，可完全在真空条件下工作。',
            descriptionEn: 'The DV7 Series High Pressure Spring Diaphragm Valve stem has a spring reset and can operate under full vacuum conditions.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'metering-valve',
        name: '计量阀',
        nameEn: 'metering valve',
        nameJa: 'メーターバルブ',
        nameKo: '계량 밸브',
        nameFr: 'Valve de dosage',
        nameAr: 'صمام القياس',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'bsm-metering-valve',
            name: '波纹管计量阀 BSM系列',
            nameEn: 'Bellows metering valve BSM series',
            nameJa: 'ベローズメーターバルブ BSMシリーズ',
            nameKo: '벨로우 미터링 밸브 BSM 시리즈',
            nameFr: 'Vanne doseuse à soufflet série BSM',
            nameAr: 'صمام قياس المنفاخ سلسلة BSM',
            model: 'BSM',
            image: '/uploads/products/xinval/metering-valve_bsm-metering-valve_1.jpg',
            images: ["/uploads/products/xinval/metering-valve_bsm-metering-valve_1.jpg"],
            description: '可实现重复的流量调节、或使用螺丝刀进行流量设定调节。',
            descriptionEn: 'Repeated flow adjustment can be achieved, or flow setting adjustment can be performed using a screwdriver.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'pressure-reducing-valve',
        name: '减压阀',
        nameEn: 'pressure reducing valve',
        nameJa: '減圧弁',
        nameKo: '감압 밸브',
        nameFr: 'vanne de réduction de pression',
        nameAr: 'صمام تخفيض الضغط',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'pre1-pressure-reducing-valve',
            name: '小流量减压阀 PRE1系列',
            nameEn: 'Small flow pressure reducing valve PRE1 series',
            nameJa: '小流量減圧弁 PRE1シリーズ',
            nameKo: '소유량 감압밸브 PRE1 시리즈',
            nameFr: 'Vanne réductrice de pression à petit débit série PRE1',
            nameAr: 'صمام تخفيض ضغط التدفق الصغير سلسلة PRE1',
            model: 'PRE1',
            image: '/uploads/products/xinval/pressure-reducing-valve_pre1-pressure-reducing-valve_1.jpg',
            images: ["/uploads/products/xinval/pressure-reducing-valve_pre1-pressure-reducing-valve_1.jpg"],
            description: '阀体使用316L/316L VAR，阀座：PCTFE/Vespel，膜片和阀芯 采用Hastelloy。',
            descriptionEn: 'The valve body is made of 316L/316L VAR, the valve seat is made of PCTFE/Vespel, and the diaphragm and spool are made of Hastelloy.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'pre2-pressure-reducing-valve',
            name: '小流量灵敏减压阀 PRE2系列',
            nameEn: 'Small Flow Sensitive Pressure Reducing Valve PRE2 Series',
            nameJa: '小流量感応減圧弁 PRE2シリーズ',
            nameKo: '작은 흐름 민감한 감압 밸브 PRE2 시리즈',
            nameFr: 'Vanne réductrice de pression sensible à petit débit série PRE2',
            nameAr: 'صمام تخفيض الضغط الحساس للتدفق الصغير سلسلة PRE2',
            model: 'PRE2',
            image: '/uploads/products/xinval/pressure-reducing-valve_pre2-pressure-reducing-valve_1.jpg',
            images: ["/uploads/products/xinval/pressure-reducing-valve_pre2-pressure-reducing-valve_1.jpg"],
            description: '阀体使用316L/316L VAR，阀座：PCTFE/Vespel，膜片和阀芯 采用Hastelloy。',
            descriptionEn: 'The valve body is made of 316L/316L VAR, the valve seat is made of PCTFE/Vespel, and the diaphragm and spool are made of Hastelloy.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'pre3-pressure-reducing-valve',
            name: '大流量灵敏减压阀 PRE3系列',
            nameEn: 'High-flow sensitive pressure reducing valve PRE3 series',
            nameJa: '大流量感応減圧弁 PRE3 シリーズ',
            nameKo: '대형 유량 민감한 압력 감소 밸브 PRE3 시리즈',
            nameFr: 'Vanne réductrice de pression sensible à grand débit série PRE3',
            nameAr: 'صمام تخفيض الضغط الحساس للتدفق الكبير من سلسلة PRE3',
            model: 'PRE3',
            image: '/uploads/products/xinval/pressure-reducing-valve_pre3-pressure-reducing-valve_1.jpg',
            images: ["/uploads/products/xinval/pressure-reducing-valve_pre3-pressure-reducing-valve_1.jpg"],
            description: '阀体使用316L/316L VAR，阀座：PCTFE/Vespel，膜片和阀芯 采用Hastelloy。',
            descriptionEn: 'The valve body is made of 316L/316L VAR, the valve seat is made of PCTFE/Vespel, and the diaphragm and spool are made of Hastelloy.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'prt1-pressure-reducing-valve',
            name: '小流量减压阀 PRT1系列',
            nameEn: 'Small flow pressure reducing valve PRT1 series',
            nameJa: '小流量減圧弁 PRT1シリーズ',
            nameKo: '소유량 감압 밸브 PRT1 시리즈',
            nameFr: 'Vanne réductrice de pression à petit débit série PRT1',
            nameAr: 'صمام تخفيض ضغط التدفق الصغير سلسلة PRT1',
            model: 'PRT1',
            image: '/uploads/products/xinval/pressure-reducing-valve_prt1-pressure-reducing-valve_1.jpg',
            images: ["/uploads/products/xinval/pressure-reducing-valve_prt1-pressure-reducing-valve_1.jpg"],
            description: '阀体使用316L/316L VAR，阀座：PCTFE/Vespel，膜片和阀芯 采用Hastelloy。',
            descriptionEn: 'The valve body is made of 316L/316L VAR, the valve seat is made of PCTFE/Vespel, and the diaphragm and spool are made of Hastelloy.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'prt2-pressure-reducing-valve',
            name: '小流量灵敏减压阀 PRT2系列',
            nameEn: 'Small Flow Sensitive Pressure Reducing Valve PRT2 Series',
            nameJa: '小流量感応減圧弁 PRT2シリーズ',
            nameKo: '작은 흐름 민감한 감압 밸브 PRT2 시리즈',
            nameFr: 'Vanne réductrice de pression sensible à petit débit série PRT2',
            nameAr: 'صمام تخفيض الضغط الحساس للتدفق الصغير سلسلة PRT2',
            model: 'PRT2',
            image: '/uploads/products/xinval/pressure-reducing-valve_prt2-pressure-reducing-valve_1.jpg',
            images: ["/uploads/products/xinval/pressure-reducing-valve_prt2-pressure-reducing-valve_1.jpg"],
            description: '阀体使用316L/316L VAR，阀座：PCTFE/Vespel，膜片和阀芯 采用Hastelloy。',
            descriptionEn: 'The valve body is made of 316L/316L VAR, the valve seat is made of PCTFE/Vespel, and the diaphragm and spool are made of Hastelloy.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'prt3-pressure-reducing-valve',
            name: '大流量灵敏减压阀 PRT3系列',
            nameEn: 'High-flow sensitive pressure reducing valve PRT3 series',
            nameJa: '大流量感応減圧弁 PRT3シリーズ',
            nameKo: '대형 유량 민감한 압력 감소 밸브 PRT3 시리즈',
            nameFr: 'Vanne réductrice de pression sensible à grand débit série PRT3',
            nameAr: 'صمام تخفيض الضغط الحساس للتدفق الكبير سلسلة PRT3',
            model: 'PRT3',
            image: '/uploads/products/xinval/pressure-reducing-valve_prt3-pressure-reducing-valve_1.jpg',
            images: ["/uploads/products/xinval/pressure-reducing-valve_prt3-pressure-reducing-valve_1.jpg"],
            description: '阀体使用316L/316L VAR，阀座：PCTFE/Vespel，膜片和阀芯 采用Hastelloy。',
            descriptionEn: 'The valve body is made of 316L/316L VAR, the valve seat is made of PCTFE/Vespel, and the diaphragm and spool are made of Hastelloy.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'check-valve',
        name: '单向阀',
        nameEn: 'Check valve',
        nameJa: 'チェック弁',
        nameKo: '일방향 밸브',
        nameFr: 'Clapet anti-retour',
        nameAr: 'صمام اتجاه واحد',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'cv3-check-valve',
            name: '全焊接单向阀 CV3系列',
            nameEn: 'Fully welded check valve CV3 series',
            nameJa: '全溶接チェックバルブ CV3シリーズ',
            nameKo: '완전 용접 체크 밸브 CV3 시리즈',
            nameFr: 'Clapet anti-retour entièrement soudée série CV3',
            nameAr: 'صمام اتجاه واحد ملحوم بالكامل سلسلة CV3',
            model: 'CV3',
            image: '/uploads/products/xinval/check-valve_cv3-check-valve_1.jpg',
            images: ["/uploads/products/xinval/check-valve_cv3-check-valve_1.jpg"],
            description: '全焊接设计，可选择标准或高纯度润湿表面抛光精度，多种端口类型和尺寸可选，适用于高纯及超高纯应用。',
            descriptionEn: 'Fully welded design with standard or high-purity wet surface polishing precision options, and a variety of port types and sizes available, suitable for high-purity and ultra-high-purity applications.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'ball-valve',
        name: '球阀',
        nameEn: 'ball valve',
        nameJa: 'ボールバルブ',
        nameKo: '볼 밸브',
        nameFr: 'vanne à sphère',
        nameAr: 'صمام كروي',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'bv1-ball-valve',
            name: '一体式仪表球阀 BV1系列',
            nameEn: 'Integrated instrument ball valve BV1 series',
            nameJa: '一体型メーターボールバルブ BV1シリーズ',
            nameKo: '일체형 계측기 볼 밸브 BV1 시리즈',
            nameFr: 'Vanne à sphère d\'instrument intégrée série BV1',
            nameAr: 'صمام كروي متكامل من سلسلة BV1',
            model: 'BV1',
            image: '/uploads/products/xinval/ball-valve_bv1-ball-valve_1.jpg',
            images: ["/uploads/products/xinval/ball-valve_bv1-ball-valve_1.jpg"],
            description: 'BV1 系列一体式仪表球阀，工作压力可达 207 bar (3000 psig)，气动执行器可供选择，多种端口类型和尺寸可选。',
            descriptionEn: 'The BV1 series integrated instrument ball valves offer operating pressures up to 207 bar (3000 psig), pneumatic actuators are available, and a variety of port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bv2-ball-valve',
            name: '三片式球阀 BV2系列',
            nameEn: 'Three-piece ball valve BV2 series',
            nameJa: '3ピースボールバルブ BV2シリーズ',
            nameKo: '3 조각 볼 밸브 BV2 시리즈',
            nameFr: 'Vanne à sphère à trois pièces série BV2',
            nameAr: 'صمام كروي ثلاثي القطع سلسلة BV2',
            model: 'BV2',
            image: '/uploads/products/xinval/ball-valve_bv2-ball-valve_1.jpg',
            images: ["/uploads/products/xinval/ball-valve_bv2-ball-valve_1.jpg"],
            description: 'BV2 系列三片式球阀，工作压力可达 69.0 bar（1000 psig），工作温度范围： -28 ℃ 至 232 ℃（ -20 ℉ 至 450 ℉ ），多种端口类型和尺寸可选。',
            descriptionEn: 'BV2 series three-piece ball valves with operating pressures up to 69.0 bar (1000 psig), operating temperature range: -28 ℃ to 232 ℃ (-20 ℉ to 450 ℉), and a variety of port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bv3-ball-valve',
            name: '三片式球阀 BV3系列',
            nameEn: 'Three-piece ball valve BV3 series',
            nameJa: '3ピースボールバルブ BV3シリーズ',
            nameKo: '3 조각 볼 밸브 BV3 시리즈',
            nameFr: 'Vanne à sphère à trois pièces série BV3',
            nameAr: 'صمام كروي ثلاثي القطع سلسلة BV3',
            model: 'BV3',
            image: '/uploads/products/xinval/ball-valve_bv3-ball-valve_1.jpg',
            images: ["/uploads/products/xinval/ball-valve_bv3-ball-valve_1.jpg"],
            description: 'BV3 系列三片式球阀，工作压力可达 207 bar（3000 psig），工作温度范围： -28 ℃ 至 232 ℃（ -20 ℉ 至 450 ℉ ），多种端口类型和尺寸可选。',
            descriptionEn: 'BV3 series three-piece ball valves with operating pressures up to 207 bar (3000 psig), operating temperature range: -28 ℃ to 232 ℃ (-20 ℉ to 450 ℉), and a variety of port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bv4-ball-valve',
            name: '冷拔棒料球阀 BV4系列',
            nameEn: 'Cold-drawn bar ball valve BV4 series',
            nameJa: '冷間引抜バーボールバルブ BV4 シリーズ',
            nameKo: '냉간 인발 바 볼 밸브 BV4 시리즈',
            nameFr: 'Vanne à bille à barre tirée à froid série BV4',
            nameAr: 'صمام كروي شريطي مرسوم على البارد سلسلة BV4',
            model: 'BV4',
            image: '/uploads/products/xinval/ball-valve_bv4-ball-valve_1.jpg',
            images: ["/uploads/products/xinval/ball-valve_bv4-ball-valve_1.jpg"],
            description: 'BV4 系列冷拔棒料球阀，工作压力可达 690 bar (10000 psig)，流通能力强；嵌入式固定阀座，阀座承压能力高，适用高压工况；气动执行器可供选择，多种端口类型和尺寸可选。',
            descriptionEn: 'The BV4 series cold-drawn bar ball valves have a working pressure of up to 690 bar (10,000 psig) and strong circulation capacity; The embedded fixed valve seat has high pressure capacity and is suitable for high-pressure working conditions; Pneumatic actuators are available, and a variety of port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bv5-ball-valve',
            name: '六方棒料球阀 BV5和BV5C系列',
            nameEn: 'Hexagonal bar ball valves BV5 and BV5C series',
            nameJa: '六角形バーボールバルブ BV5 および BV5C シリーズ',
            nameKo: '육각형 바 볼 밸브 BV5 및 BV5C 시리즈',
            nameFr: 'Vannes à bille à barre hexagonale série BV5 et BV5C',
            nameAr: 'صمام كروي شريطي سداسي الأطراف سلسلة BV5 و BV5C',
            model: 'BV5/BV5C',
            image: '/uploads/products/xinval/ball-valve_bv5-ball-valve_1.jpg',
            images: ["/uploads/products/xinval/ball-valve_bv5-ball-valve_1.jpg"],
            description: 'BV5 系列和 BV5C 系列六方棒料球阀，结构紧凑，操作扭矩小；可对 BV5 系列阀门进行锁定，05、07、10 通径阀门锁孔直径为 4.8 mm (0.19 in.) ，12、16 通径阀门锁孔直径为 5.7 mm (0.22 in.) ；防飞出阀杆结构，多种端口型号和尺寸可供选择。',
            descriptionEn: 'BV5 series and BV5C series hexagonal rod ball valves, compact structure, low operating torque; BV5 series valves can be locked, with a keyhole diameter of 4.8 mm (0.19 in.) for 05, 07, and 10-gauge valves and a keyhole diameter of 5.7 mm (0.22 in.) for 12 and 16-gauge valves. Anti-fly-out valve stem structure, various port models and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bv6-ball-valve',
            name: '耳轴球阀 BV6和BV6H系列',
            nameEn: 'Trunnion Ball Valves BV6 and BV6H Series',
            nameJa: 'トラニオンボールバルブ BV6 および BV6H シリーズ',
            nameKo: '트러니언 볼 밸브 BV6 및 BV6H 시리즈',
            nameFr: 'Vannes à bille à tourillon série BV6 et BV6H',
            nameAr: 'صمام كروي ترونيون سلسلة BV6 و BV6H',
            model: 'BV6/BV6H',
            image: '',
            images: [],
            description: 'BV6 和 BV6H 系列耳轴型球阀，工作压力可达 690 bar (10000 psig)，具有防阀球冲出和防阀杆飞出结构，操作扭矩小，阀座自动预警密封，弹簧加载阀座，在低压和高压系统内都具有防漏完整性降低压力突变引起的阀座磨损。',
            descriptionEn: 'The BV6 and BV6H series trunnion ball valves, with operating pressures up to 690 bar (10,000 psig), feature anti-ball ejection and anti-stem ejection structures, low operating torque, automatic seat early warning sealing, and spring-loaded seats. They provide leak-proof integrity in both low- and high-pressure systems to reduce seat wear caused by sudden pressure changes.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bv7-ball-valve',
            name: '高性能球阀 BV7系列',
            nameEn: 'High Performance Ball Valve BV7 Series',
            nameJa: '高性能ボールバルブ BV7シリーズ',
            nameKo: '고성능 볼 밸브 BV7 시리즈',
            nameFr: 'Vanne à sphère haute performance série BV7',
            nameAr: 'صمام كروي عالي الأداء سلسلة BV7',
            model: 'BV7',
            image: '',
            images: [],
            description: 'BV7 系列高性能球阀，工作压力可达 414 bar ( 6000 psig )，承压能力强，操作扭矩小。',
            descriptionEn: 'The BV7 series of high-performance ball valves offers a working pressure of up to 414 bar (6000 psig), strong pressure capacity, and low operating torque.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'needle-valve',
        name: '针阀',
        nameEn: 'needle valve',
        nameJa: 'ニードル弁',
        nameKo: '니들 밸브',
        nameFr: 'vanne aiguille',
        nameAr: 'صمام الإبرة',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'nv1-needle-valve',
            name: '锻造阀体针阀 NV1系列',
            nameEn: 'Forged Valve Body Needle Valve NV1 Series',
            nameJa: '鍛造ボディニードルバルブ NV1シリーズ',
            nameKo: '단조 바디 니들 밸브 NV1 시리즈',
            nameFr: 'Vanne à aiguille à corps forgé série NV1',
            nameAr: 'صمام إبرة جسم مزور سلسلة NV1',
            model: 'NV1',
            image: '/uploads/products/xinval/needle-valve_nv1-needle-valve_1.jpg',
            images: ["/uploads/products/xinval/needle-valve_nv1-needle-valve_1.jpg"],
            description: 'NV1 系列锻造阀体针阀，一体式锻造阀体，NV1 系列（标准）工作压力可达6000 psig，NV1H 系列（高压）工作压力可达10000 psig；采用两截式阀杆设计，开关时阀头仅上下运动，减少每个行程对填料的磨损；手柄稳固耐用，多种端口类型和尺寸可选。',
            descriptionEn: 'NV1 series forged valve body needle valve, one-piece forged valve body, NV1 series (standard) working pressure up to 6000 psig, NV1H series (high pressure) working pressure up to 10000 psig; Adopting a two-section valve stem design, the valve head only moves up and down during switching, reducing the wear of the packing material in each stroke; The handle is sturdy and durable, and a variety of port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'nv2-needle-valve',
            name: '螺纹阀帽针阀 NV2系列',
            nameEn: 'Threaded Cap Needle Valve NV2 Series',
            nameJa: 'ねじキャップニードルバルブ NV2シリーズ',
            nameKo: '나사 캡 니들 밸브 NV2 시리즈',
            nameFr: 'Vanne à aiguille à capot fileté série NV2',
            nameAr: 'صمام إبرة غطاء ملولب سلسلة NV2',
            model: 'NV2',
            image: '',
            images: [],
            description: 'NV2 系列螺纹阀帽针阀，冷拉四方棒料加工阀体，与阀帽连接可靠，工作压力可达 414 bar (6000 psig)；采用两截式阀杆设计，开关时阀头仅上下运动，减少每个行程对填料的磨损；手柄稳固耐用，多种端口类型和尺寸可选。',
            descriptionEn: 'NV2 series threaded valve cap needle valve, cold-drawn square bar processed valve body, reliable connection to valve cap, working pressure up to 414 bar (6000 psig); Adopting a two-section valve stem design, the valve head only moves up and down during switching, reducing the wear of the packing material in each stroke; The handle is sturdy and durable, and a variety of port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'nv3-needle-valve',
            name: '整体式阀帽针阀 NV3系列',
            nameEn: 'Integral valve cap needle valve NV3 series',
            nameJa: '一体型キャップニードルバルブ NV3シリーズ',
            nameKo: '일체형 캡 니들 밸브 NV3 시리즈',
            nameFr: 'Vanne à aiguille à capot monobloc série NV3',
            nameAr: 'صمام إبرة غطاء الصمام المتكامل سلسلة NV3',
            model: 'NV3',
            image: '/uploads/products/xinval/needle-valve_nv3-needle-valve_1.jpg',
            images: ["/uploads/products/xinval/needle-valve_nv3-needle-valve_1.jpg"],
            description: 'NV3 系列整体式阀帽针阀，一体式锻造阀体，NV3 系列（标准）工作压力可达3000 psig，NV3H 系列（高压）工作压力可达5000 psig；碟簧自动补偿填料密封系统；多种端口类型和尺寸可选。',
            descriptionEn: 'NV3 series integral valve cap needle valve, integral forged valve body, NV3 series (standard) working pressure up to 3000 psig, NV3H series (high pressure) working pressure up to 5000 psig; Disc spring automatic compensation packing sealing system; Multiple port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'nv4-needle-valve',
            name: '非旋转阀杆针阀 NV4系列',
            nameEn: 'Non-rotary valve stem needle valve NV4 series',
            nameJa: '非回転ステムニードルバルブ NV4シリーズ',
            nameKo: '비회전 스템 니들 밸브 NV4 시리즈',
            nameFr: 'Vanne à aiguille à tige non rotative série NV4',
            nameAr: 'صمام إبرة الجذع غير الدوار سلسلة NV4',
            model: 'NV4',
            image: '',
            images: [],
            description: 'NV4 系列非旋转阀杆针阀，采用一体式锻造阀体，结构紧凑，直通型和角型结构可选，工作压力可达 3000 psig；非旋转阀杆设计，延长了阀门使用寿命；O 形密封圈，操作力矩小；多种端口类型和尺寸可选。',
            descriptionEn: 'The NV4 series non-rotating stem and needle valves feature a one-piece forged valve body, a compact structure, straight-through and angle-type options, and a working pressure of up to 3000 psig. The non-rotating valve stem design extends the valve\'s service life; O-ring seal, low operating torque; Multiple port types and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'nv5-needle-valve',
            name: '活接阀帽针阀 NV5系列',
            nameEn: 'Flexible connection valve cap needle valve NV5 series',
            nameJa: 'ユニオンキャップニードルバルブ NV5シリーズ',
            nameKo: '연결 캡 니들 밸브 NV5 시리즈',
            nameFr: 'Vanne à aiguille à capot à raccordement série NV5',
            nameAr: 'صمام إبرة غطاء التوصيل سلسلة NV5',
            model: 'NV5',
            image: '/uploads/products/xinval/needle-valve_nv5-needle-valve_1.jpg',
            images: ["/uploads/products/xinval/needle-valve_nv5-needle-valve_1.jpg"],
            description: 'NV5 系列活接阀帽针阀，一体式锻造阀体，NV5 系列（标准）工作压力可达6000 psig，NV5H 系列（高压）工作压力可达10000 psig。',
            descriptionEn: 'NV5 Series Flexible Cap Needle Valve, One-piece forged body, NV5 Series (standard) working pressure up to 6000 psig, NV5H Series (high pressure) working pressure up to 10000 psig.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'nv6-needle-valve',
            name: 'OS&Y 结构针阀 NV6系列',
            nameEn: 'OS&Y Structural Needle Valves NV6 Series',
            nameJa: 'OS&Y構造 ニードルバルブ NV6シリーズ',
            nameKo: 'OS&Y 구조 니들 밸브 NV6 시리즈',
            nameFr: 'Soupape à aiguille de structure OS&Y série NV6',
            nameAr: 'صمام إبرة هيكل OS&Y سلسلة NV6',
            model: 'NV6',
            image: '',
            images: [],
            description: 'NV6 系列 OS&Y 结构针阀，采用冷拉四方棒阀体设计，工作压力可达 6000 psig；两截式阀杆设计，开关时阀头仅上下运动，减少每个行程对填料的磨损；阀杆螺纹位于填料上方，避免螺纹润滑脂与系统介质接触；多种填料材料、端口类型和尺寸可选。',
            descriptionEn: 'The NV6 series OS&Y needle valves feature a cold-drawn square rod body design and can operate at a pressure of up to 6000 psig. The two-section valve stem design allows the valve head to only move up and down during switching, reducing the wear of the packing material during each stroke. The valve stem thread is located above the packing material to avoid contact between the thread grease and the system medium; A variety of filler materials, port types, and sizes are available.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'bellows-valve',
        name: '波纹管阀',
        nameEn: 'bellows valve',
        nameJa: 'ベローズバルブ',
        nameKo: '벨로우 밸브',
        nameFr: 'Vanne à soufflet',
        nameAr: 'صمام منفاخ',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'bsv1-bellows-valve',
            name: '波纹管阀 BSV1系列',
            nameEn: 'Bellows Valve BSV1 Series',
            nameJa: 'ベローズバルブ BSV1シリーズ',
            nameKo: '벨로우 밸브 BSV1 시리즈',
            nameFr: 'Vanne à soufflet série BSV1',
            nameAr: 'صمام منفاخ سلسلة BSV1',
            model: 'BSV1',
            image: '/uploads/products/xinval/bellows-valve_bsv1-bellows-valve_1.jpg',
            images: ["/uploads/products/xinval/bellows-valve_bsv1-bellows-valve_1.jpg"],
            description: 'BSV1 系列波纹管阀阀体材质为不锈钢，工作压力达 69.0 bar (1000 psig)，工作温度范围为 -28°C 至 450°C (-20°F 至 842°F)。',
            descriptionEn: 'The BSV1 Series bellows valve body is made of stainless steel and has an operating pressure of 69.0 bar (1000 psig) and an operating temperature range of -28°C to 450°C (-20°F to 842°F).',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'bsv2-bellows-valve',
            name: '波纹管阀 BSV2系列',
            nameEn: 'Bellows Valve BSV2 Series',
            nameJa: 'ベローズバルブ BSV2シリーズ',
            nameKo: '벨로우 밸브 BSV2 시리즈',
            nameFr: 'Vanne à soufflet série BSV2',
            nameAr: 'صمام منفاخ سلسلة BSV2',
            model: 'BSV2',
            image: '/uploads/products/xinval/bellows-valve_bsv2-bellows-valve_1.jpg',
            images: ["/uploads/products/xinval/bellows-valve_bsv2-bellows-valve_1.jpg"],
            description: 'BSV2 系列波纹管阀阀体材质为不锈钢，工作压力达 172 bar (2500 psig)，工作温度范围为 -28°C 至 450°C (-20°F 至 842°F)。',
            descriptionEn: 'The BSV2 Series bellows valve body is made of stainless steel and has an operating pressure of 172 bar (2500 psig) and an operating temperature range of -28°C to 450°C (-20°F to 842°F).',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
    ],
  },
  {
    id: 'filters',
    name: '过滤器',
    nameEn: 'Filters',
    nameJa: 'フィルター',
    nameKo: '필터',
    nameFr: 'Filtres',
    nameAr: 'المرشحات',
    purchaseMode: 'quote',
    categories: [
      {
        id: 'gas-filter',
        name: '气体过滤器',
        nameEn: 'gas filter',
        nameJa: 'ガスフィルター',
        nameKo: '가스 필터',
        nameFr: 'Filtre à gaz',
        nameAr: 'فلتر الغاز',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'ft4-gas-filter',
            name: '粉末烧结滤芯过滤器 FT4系列',
            nameEn: 'Powder Sintered Cartridge Filter FT4 Series',
            nameJa: '粉末焼結エレメントフィルター FT4シリーズ',
            nameKo: '분말 소결 필터 필터 FT4 시리즈',
            nameFr: 'Filtre à élément de frittage à poudre série FT4',
            nameAr: 'مرشح عنصر مرشح مسحوق متلبد سلسلة FT4',
            model: 'FT4系列',
            image: '/uploads/products/xinval/gas-filter_ft4-gas-filter_1.jpg',
            images: ["/uploads/products/xinval/gas-filter_ft4-gas-filter_1.jpg"],
            description: 'FT4 系列气体过滤器选材和制造符合高洁净度环境的要求，确保流体的纯度和质量。',
            descriptionEn: 'The FT4 series gas filters are selected and manufactured to meet the requirements of a high-cleanliness environment, ensuring the purity and quality of the fluid.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'ft5-gas-filter',
            name: '陶瓷滤芯过滤器 FT5系列',
            nameEn: 'Ceramic Cartridge Filter FT5 Series',
            nameJa: 'セラミックカートリッジフィルター FT5シリーズ',
            nameKo: '세라믹 필터 필터 FT5 시리즈',
            nameFr: 'Filtre à cartouche en céramique série FT5',
            nameAr: 'مرشح عنصر فلتر السيراميك سلسلة FT5',
            model: 'FT5系列',
            image: '/uploads/products/xinval/gas-filter_ft5-gas-filter_1.jpg',
            images: ["/uploads/products/xinval/gas-filter_ft5-gas-filter_1.jpg"],
            description: 'FT5 系列气体过滤器选材和制造符合高洁净度环境的要求，确保流体的纯度和质量。',
            descriptionEn: 'The FT5 series gas filters are selected and manufactured to meet the requirements of a high-cleanliness environment, ensuring the purity and quality of the fluid.',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: 'ft6-gas-filter',
            name: '不锈钢滤芯过滤器 FT6系列',
            nameEn: 'Stainless steel cartridge filter FT6 series',
            nameJa: 'ステンレスカートリッジフィルター FT6シリーズ',
            nameKo: '스테인레스 스틸 필터 요소 필터 FT6 시리즈',
            nameFr: 'Filtre à cartouche en acier inoxydable série FT6',
            nameAr: 'مرشح الفولاذ المقاوم للصدأ سلسلة FT6',
            model: 'FT6系列',
            image: '/uploads/products/xinval/gas-filter_ft6-gas-filter_1.jpg',
            images: ["/uploads/products/xinval/gas-filter_ft6-gas-filter_1.jpg"],
            description: 'FT6 系列气体过滤器选材和制造符合高洁净度环境的要求，确保流体的纯度和质量。',
            descriptionEn: 'The FT6 series gas filters are selected and manufactured to meet the requirements of a high-cleanliness environment, ensuring the purity and quality of the fluid.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
    ],
  },
  {
    id: 'manifolds',
    name: '阀组',
    nameEn: 'Valve Manifolds',
    nameJa: 'マニホールド',
    nameKo: '밸브 매니폴드',
    nameFr: 'Collecteurs de vannes',
    nameAr: 'مجموعات الصمامات',
    purchaseMode: 'quote',
    categories: [
      {
        id: 'gauge-valve',
        name: '表阀',
        nameEn: 'Gauge valve',
        nameJa: 'ゲージバルブ',
        nameKo: '게이지 밸브',
        nameFr: 'Vanne de jauge',
        nameAr: 'صمام قياس',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: 'gv-gauge-valve',
            name: '表阀 GV和GVH系列',
            nameEn: 'Gauge Valves GV and GVH Series',
            nameJa: 'ゲージバルブ GV および GVH シリーズ',
            nameKo: '게이지 밸브 GV 및 GVH 시리즈',
            nameFr: 'Vannes de jauge série GV et GVH',
            nameAr: 'صمامات القياس سلسلة GV و GVH',
            model: 'GV/GVH',
            image: '',
            images: [],
            description: '表阀能够在狭小的空间内运行，并能抵御低水平的腐蚀。',
            descriptionEn: 'Gauge valves can operate in confined spaces and are resistant to low levels of corrosion.',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
      {
        id: 'instrument-manifold',
        name: '仪表阀组',
        nameEn: 'instrument valve group',
        nameJa: '計器用マニホールド',
        nameKo: '계측기 밸브 그룹',
        nameFr: 'Groupe de vannes d\'instrument',
        nameAr: 'مجموعة صمامات الأدوات',
        icon: 'Package',
        description: '',
        descriptionEn: '',
        models: [
          {
            id: '2d-instrument-manifold',
            name: '二阀组 2D、2R、2DH、2RH系列',
            nameEn: 'Two valve groups 2D, 2R, 2DH, 2RH series',
            nameJa: '二弁群 2D、2R、2DH、2RHシリーズ',
            nameKo: '2 밸브 그룹 2D, 2R, 2DH, 2RH 시리즈',
            nameFr: 'Deux groupes de vannes série 2D, 2R, 2DH, 2RH',
            nameAr: 'مجموعة صمامين 2D ، 2R ، 2DH ، سلسلة 2RH',
            model: '2D/2R/2DH/2RH',
            image: '/uploads/products/xinval/instrument-manifold_2d-instrument-manifold_1.jpg',
            images: ["/uploads/products/xinval/instrument-manifold_2d-instrument-manifold_1.jpg"],
            description: '所有阀组在出厂前均以额定工作压力进行密封测试',
            descriptionEn: 'All valve assemblies are seal tested at rated working pressure before leaving the factory',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: '3d-instrument-manifold',
            name: '三阀组 3D、3R、3DH、3RH系列',
            nameEn: 'Three-valve set 3D, 3R, 3DH, 3RH series',
            nameJa: '3つのバルブ群 3D、3R、3DH、3RHシリーズ',
            nameKo: '3 밸브 그룹 3D, 3R, 3DH, 3RH 시리즈',
            nameFr: 'Trois groupes de vannes 3D, 3R, 3DH, série 3RH',
            nameAr: 'ثلاثة مجموعات صمامات سلسلة 3D ، 3R ، 3DH ، 3RH',
            model: '3D/3R/3DH/3RH',
            image: '',
            images: [],
            description: '所有阀组在出厂前均以额定工作压力进行密封测试',
            descriptionEn: 'All valve assemblies are seal tested at rated working pressure before leaving the factory',
            specs: [],
            purchaseMode: 'quote',
          },
          {
            id: '5d-instrument-manifold',
            name: '五阀组 5D、5R、5DH、5RH系列',
            nameEn: 'Five-valve group 5D, 5R, 5DH, 5RH series',
            nameJa: '5バルブ群 5D、5R、5DH、5RHシリーズ',
            nameKo: '5 밸브 그룹 5D, 5R, 5DH, 5RH 시리즈',
            nameFr: 'Cinq groupes de vannes série 5D, 5R, 5DH, 5RH',
            nameAr: 'خمسة مجموعات صمامات سلسلة 5D ، 5R ، 5DH ، 5RH',
            model: '5D/5R/5DH/5RH',
            image: '',
            images: [],
            description: '所有阀组在出厂前均以额定工作压力进行密封测试',
            descriptionEn: 'All valve assemblies are seal tested at rated working pressure before leaving the factory',
            specs: [],
            purchaseMode: 'quote',
          },
        ],
      },
    ],
  },
];
